//! 已校验片段到稳定 Rust 静态数据的生成逻辑。

use super::LoadedSpec;

pub(super) fn generate_registry(specs: &[LoadedSpec]) -> String {
    let mut output =
        String::from("// @generated by build_support/snippet_catalog.rs; do not edit.\n\n");
    output.push_str("pub(super) static STATIC_SNIPPET_CATALOG: &[StaticSnippetCatalogItem] = &[\n");
    for loaded in specs {
        let spec = &loaded.spec;
        output.push_str("    StaticSnippetCatalogItem {\n");
        for (name, value) in [
            ("id", &spec.id),
            ("catalog_version", &spec.catalog_version),
            ("pack", &spec.pack),
            ("category", &spec.category),
            ("title", &spec.title),
            ("description", &spec.description),
            ("template", &spec.template),
            ("command_spec", &spec.command_spec),
            ("owner", &spec.owner),
            ("tested_version", &spec.tested_version),
            ("updated_at", &spec.updated_at),
        ] {
            output.push_str(&format!("        {name}: {value:?},\n"));
        }
        output.push_str(&format!("        sort_order: {},\n", spec.sort_order));
        output.push_str(&format!(
            "        capabilities: &{:?},\n",
            spec.capabilities
        ));
        output.push_str(&format!("        tags: &{:?},\n", spec.tags));
        output.push_str(&format!("        sensitive: {},\n", spec.sensitive));
        output.push_str(&format!("        deprecated: {},\n", spec.deprecated));
        output.push_str(&format!(
            "        source_name: {:?},\n        source_url: {:?},\n",
            spec.source.name, spec.source.url
        ));
        let platform_mask = spec
            .platforms
            .iter()
            .fold(0, |mask, item| mask | item.mask());
        let shell_mask = spec.shells.iter().fold(0, |mask, item| mask | item.mask());
        output.push_str(&format!("        scope: {:?},\n        platform_mask: {platform_mask},\n        shell_mask: {shell_mask},\n        risk: {:?},\n        duration: {:?},\n        default_action: {:?},\n", spec.scope.value(), spec.risk.value(), spec.duration.value(), spec.default_action.value()));
        output.push_str("        variables: &[\n");
        for variable in &spec.variables {
            output.push_str(&format!("            StaticSnippetVariable {{ name: {:?}, label: {:?}, description: {:?}, kind: {:?}, required: {}, default_value: {:?}, suggestions: &{:?}, validation: {:?}, render_strategy: {:?}, sensitive: {} }},\n", variable.name, variable.label, variable.description, variable.kind.value(), variable.required, variable.default_value, variable.suggestions, variable.validation, variable.render_strategy.value(), variable.sensitive));
        }
        output.push_str("        ],\n    },\n");
    }
    output.push_str("];\n");
    output
}
