//! 内置快捷键默认值。
//!
//! @author kongweiguang

use super::{KeybindingScope, KeybindingSetting};

/// 第一批内置快捷键，后续由 action registry 接管。
pub fn default_keybindings() -> Vec<KeybindingSetting> {
    vec![
        keybinding(
            "settings.open",
            "打开设置",
            "参考 IntelliJ IDEA 的设置入口：Windows 使用 Ctrl+Alt+S，macOS 使用 Cmd+,。",
            "Ctrl+Alt+S",
            "Ctrl+Alt+S",
            "Cmd+,",
            KeybindingScope::Global,
        ),
        keybinding(
            "settings.keybindings",
            "查看快捷键与动作",
            "参考 IDEA 的 Find Action 习惯，当前直接打开快捷键与动作列表。",
            "Ctrl+Shift+A",
            "Ctrl+Shift+A",
            "Cmd+Shift+A",
            KeybindingScope::Global,
        ),
        keybinding(
            "terminal.focus",
            "回到终端",
            "参考 IDEA Terminal 工具窗口；显示终端工作区并收起右侧工具面板。",
            "Alt+F12",
            "Alt+F12",
            "Option+F12",
            KeybindingScope::Global,
        ),
        keybinding(
            "terminal.newTab",
            "新建本地终端",
            "新建本地终端 tab，保留终端应用常见的新建标签习惯。",
            "Ctrl+Shift+T",
            "Ctrl+Shift+T",
            "Cmd+Shift+T",
            KeybindingScope::Workspace,
        ),
        keybinding(
            "terminal.closeTab",
            "关闭当前终端 tab",
            "关闭当前终端 tab，尽量贴近 IDEA 关闭编辑器 tab 的习惯。",
            "Ctrl+F4",
            "Ctrl+F4",
            "Cmd+W",
            KeybindingScope::Workspace,
        ),
        keybinding(
            "terminal.closePane",
            "关闭当前分屏",
            "关闭当前分屏；只有多分屏时生效，避免误关最后一个终端。",
            "Ctrl+Shift+W",
            "Ctrl+Shift+W",
            "Cmd+Shift+W",
            KeybindingScope::Terminal,
        ),
        keybinding(
            "terminal.splitHorizontal",
            "左右分屏",
            "在当前终端右侧创建分屏，沿用 IDEA 风格的 Ctrl/Option 方向键组合。",
            "Ctrl+Alt+Right",
            "Ctrl+Alt+Right",
            "Ctrl+Option+Right",
            KeybindingScope::Workspace,
        ),
        keybinding(
            "terminal.splitVertical",
            "上下分屏",
            "在当前终端下方创建分屏，与左右分屏形成方向键配对。",
            "Ctrl+Alt+Down",
            "Ctrl+Alt+Down",
            "Ctrl+Option+Down",
            KeybindingScope::Workspace,
        ),
        keybinding(
            "terminal.previousTab",
            "上一个终端 tab",
            "切到左侧终端 tab，参考 IDEA 在 tab/位置之间切换的方向键心智。",
            "Alt+Left",
            "Alt+Left",
            "Cmd+Shift+[",
            KeybindingScope::Workspace,
        ),
        keybinding(
            "terminal.nextTab",
            "下一个终端 tab",
            "切到右侧终端 tab，和上一个 tab 保持成对操作。",
            "Alt+Right",
            "Alt+Right",
            "Cmd+Shift+]",
            KeybindingScope::Workspace,
        ),
        keybinding(
            "tool.agentLauncher",
            "打开 Agent Launcher",
            "打开 Agent Launcher 工具窗口，参考 IDEA Alt/Cmd+数字切换工具窗口。",
            "Alt+2",
            "Alt+2",
            "Cmd+2",
            KeybindingScope::Global,
        ),
        keybinding(
            "tool.system",
            "打开系统信息",
            "打开系统信息工具窗口，使用工具窗口编号快速切换。",
            "Alt+3",
            "Alt+3",
            "Cmd+3",
            KeybindingScope::Global,
        ),
        keybinding(
            "tool.sftp",
            "打开 SFTP",
            "打开 SFTP 工具窗口，便于在终端和文件浏览之间切换。",
            "Alt+4",
            "Alt+4",
            "Cmd+4",
            KeybindingScope::Global,
        ),
        keybinding(
            "tool.ports",
            "打开端口转发",
            "打开端口转发工具窗口。",
            "Alt+5",
            "Alt+5",
            "Cmd+5",
            KeybindingScope::Global,
        ),
        keybinding(
            "tool.snippets",
            "打开脚本片段",
            "打开脚本片段工具窗口。",
            "Alt+6",
            "Alt+6",
            "Cmd+6",
            KeybindingScope::Global,
        ),
        keybinding(
            "tool.logs",
            "打开日志",
            "打开日志工具窗口，快速查看会话和操作审计记录。",
            "Alt+7",
            "Alt+7",
            "Cmd+7",
            KeybindingScope::Global,
        ),
    ]
}

fn keybinding(
    action: &str,
    label: &str,
    description: &str,
    binding: &str,
    windows_binding: &str,
    mac_binding: &str,
    scope: KeybindingScope,
) -> KeybindingSetting {
    KeybindingSetting {
        action: action.to_string(),
        binding: binding.to_string(),
        description: description.to_string(),
        editable: true,
        label: label.to_string(),
        mac_binding: mac_binding.to_string(),
        scope,
        windows_binding: windows_binding.to_string(),
    }
}
