//! 已校验 spec 到稳定 Rust 静态表的生成逻辑。
//!
//! @author kongweiguang

use std::collections::BTreeMap;

use super::{schema::Sensitivity, LoadedSpec};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum BucketKind {
    Subcommand,
    Option,
}

impl BucketKind {
    fn generated_variant(self) -> &'static str {
        match self {
            Self::Subcommand => "StaticSpecBucketKind::Subcommand",
            Self::Option => "StaticSpecBucketKind::Option",
        }
    }
}

struct GeneratedItem {
    name: String,
    description: String,
    sensitivity: Sensitivity,
    allow_inline: bool,
}

pub(super) fn generate_registry(specs: &[LoadedSpec]) -> String {
    let mut buckets = BTreeMap::<(String, Vec<String>, BucketKind), Vec<GeneratedItem>>::new();
    let mut root_items = Vec::new();
    for loaded in specs {
        let spec = &loaded.spec;
        root_items.push(GeneratedItem {
            name: spec.command.clone(),
            description: spec.description.clone(),
            sensitivity: spec.safety.sensitivity,
            allow_inline: spec.safety.allow_inline,
        });
        for subcommand in &spec.subcommands {
            buckets
                .entry((
                    spec.command.clone(),
                    subcommand.path.clone(),
                    BucketKind::Subcommand,
                ))
                .or_default()
                .push(GeneratedItem {
                    name: subcommand.name.clone(),
                    description: subcommand.description.clone(),
                    sensitivity: subcommand.safety.sensitivity,
                    allow_inline: subcommand.safety.allow_inline,
                });
        }
        for argument in &spec.arguments {
            for value in &argument.values {
                buckets
                    .entry((
                        spec.command.clone(),
                        argument.path.clone(),
                        BucketKind::Subcommand,
                    ))
                    .or_default()
                    .push(GeneratedItem {
                        name: value.clone(),
                        description: argument.description.clone(),
                        sensitivity: argument.safety.sensitivity,
                        allow_inline: argument.safety.allow_inline,
                    });
            }
        }
        for option in &spec.options {
            buckets
                .entry((
                    spec.command.clone(),
                    option.path.clone(),
                    BucketKind::Option,
                ))
                .or_default()
                .push(GeneratedItem {
                    name: option.name.clone(),
                    description: option.description.clone(),
                    sensitivity: option.safety.sensitivity,
                    allow_inline: option.safety.allow_inline,
                });
        }
    }
    root_items.sort_by(|left, right| left.name.cmp(&right.name));
    for items in buckets.values_mut() {
        let mut seen = std::collections::BTreeSet::new();
        items.retain(|item| seen.insert(item.name.clone()));
    }

    let mut output =
        String::from("// @generated by build_support/command_spec_registry.rs; do not edit.\n\n");
    write_items(&mut output, "ROOT_ITEMS", &root_items);
    let mut bucket_names = Vec::new();
    for (index, ((command, path, kind), items)) in buckets.iter().enumerate() {
        let name = format!("BUCKET_ITEMS_{index}");
        write_items(&mut output, &name, items);
        bucket_names.push((name, command, path, kind));
    }

    output.push_str("pub(super) static STATIC_SPEC_COMMANDS: &[StaticCommandSpec] = &[\n");
    for loaded in specs {
        let spec = &loaded.spec;
        let platform_mask = spec
            .platforms
            .iter()
            .fold(0, |mask, item| mask | item.mask());
        let shell_mask = spec.shells.iter().fold(0, |mask, item| mask | item.mask());
        output.push_str("    StaticCommandSpec {\n");
        output.push_str(&format!("        name: {:?},\n", spec.command));
        output.push_str(&format!("        aliases: &{:?},\n", spec.aliases));
        output.push_str(&format!("        description: {:?},\n", spec.description));
        output.push_str(&format!("        source_name: {:?},\n", spec.source.name));
        output.push_str(&format!("        source_url: {:?},\n", spec.source.url));
        output.push_str(&format!(
            "        tested_version: {:?},\n",
            spec.tested_version
        ));
        output.push_str(&format!("        owner: {:?},\n", spec.owner));
        output.push_str(&format!("        updated_at: {:?},\n", spec.updated_at));
        output.push_str(&format!("        platform_mask: {platform_mask},\n"));
        output.push_str(&format!("        shell_mask: {shell_mask},\n"));
        output.push_str("    },\n");
    }
    output.push_str("];\n\n");
    output
        .push_str("pub(super) static STATIC_SPEC_ROOT_ITEMS: &[StaticSpecItem] = ROOT_ITEMS;\n\n");
    output.push_str("pub(super) static STATIC_SPEC_BUCKETS: &[StaticSpecBucket] = &[\n");
    for (name, command, path, kind) in bucket_names {
        output.push_str("    StaticSpecBucket {\n");
        output.push_str(&format!("        command: {:?},\n", command));
        output.push_str(&format!("        path: &{:?},\n", path));
        output.push_str(&format!("        kind: {},\n", kind.generated_variant()));
        output.push_str(&format!("        items: {name},\n"));
        output.push_str("    },\n");
    }
    output.push_str("];\n");
    output
}

fn write_items(output: &mut String, name: &str, items: &[GeneratedItem]) {
    output.push_str(&format!("static {name}: &[StaticSpecItem] = &[\n"));
    for item in items {
        output.push_str("    StaticSpecItem {\n");
        output.push_str(&format!("        name: {:?},\n", item.name));
        output.push_str(&format!("        description: {:?},\n", item.description));
        output.push_str(&format!(
            "        sensitivity: {},\n",
            item.sensitivity.generated_variant()
        ));
        output.push_str(&format!("        allow_inline: {},\n", item.allow_inline));
        output.push_str("    },\n");
    }
    output.push_str("];\n\n");
}
