export function buildSftpCwdTrackingSetupScript() {
  return [
    "set -eu",
    "",
    "marker_begin='# >>> kerminal sftp cwd tracking >>>'",
    "",
    "append_bash() {",
    '    config_file="${HOME}/.bashrc"',
    '    mkdir -p "$(dirname "$config_file")"',
    '    touch "$config_file"',
    '    if grep -Fq "$marker_begin" "$config_file"; then',
    "        printf 'already configured: %s\\n' \"$config_file\"",
    "        return 0",
    "    fi",
    "    cat >> \"$config_file\" <<'KERM_CWD_BASH'",
    "# >>> kerminal sftp cwd tracking >>>",
    "__kerminal_cwd() { printf '\\033]1337;CurrentDir=%s\\007' \"$PWD\"; }",
    'case ";${PROMPT_COMMAND:-};" in',
    '  *";__kerminal_cwd;"*) ;;',
    '  *) PROMPT_COMMAND="__kerminal_cwd${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;',
    "esac",
    "# <<< kerminal sftp cwd tracking <<<",
    "KERM_CWD_BASH",
    "    printf 'configured: %s\\n' \"$config_file\"",
    "}",
    "",
    "append_zsh() {",
    '    config_file="${HOME}/.zshrc"',
    '    mkdir -p "$(dirname "$config_file")"',
    '    touch "$config_file"',
    '    if grep -Fq "$marker_begin" "$config_file"; then',
    "        printf 'already configured: %s\\n' \"$config_file\"",
    "        return 0",
    "    fi",
    "    cat >> \"$config_file\" <<'KERM_CWD_ZSH'",
    "# >>> kerminal sftp cwd tracking >>>",
    "__kerminal_cwd() { printf '\\033]1337;CurrentDir=%s\\007' \"$PWD\"; }",
    "autoload -Uz add-zsh-hook",
    "add-zsh-hook precmd __kerminal_cwd",
    "# <<< kerminal sftp cwd tracking <<<",
    "KERM_CWD_ZSH",
    "    printf 'configured: %s\\n' \"$config_file\"",
    "}",
    "",
    "append_fish() {",
    '    config_file="${HOME}/.config/fish/config.fish"',
    '    mkdir -p "$(dirname "$config_file")"',
    '    touch "$config_file"',
    '    if grep -Fq "$marker_begin" "$config_file"; then',
    "        printf 'already configured: %s\\n' \"$config_file\"",
    "        return 0",
    "    fi",
    "    cat >> \"$config_file\" <<'KERM_CWD_FISH'",
    "# >>> kerminal sftp cwd tracking >>>",
    "function __kerminal_cwd --on-event fish_prompt",
    "    printf '\\e]1337;CurrentDir=%s\\a' $PWD",
    "end",
    "# <<< kerminal sftp cwd tracking <<<",
    "KERM_CWD_FISH",
    "    printf 'configured: %s\\n' \"$config_file\"",
    "}",
    "",
    'shell_name=$(basename "${SHELL:-}")',
    'case "$shell_name" in',
    "    fish) append_fish ;;",
    "    zsh) append_zsh ;;",
    "    bash) append_bash ;;",
    "    *)",
    '        if [ -f "${HOME}/.zshrc" ] && [ ! -f "${HOME}/.bashrc" ]; then',
    "            append_zsh",
    "        else",
    "            append_bash",
    "        fi",
    "        ;;",
    "esac",
    "printf 'reload required: sign in again or source the updated shell file\\n'",
    "",
  ].join("\n");
}
