//! 片段、工作流、历史和诊断工具目录。
//!
//! @author kongweiguang

use crate::models::tool_registry::{
    ToolAuditPolicy, ToolCategory, ToolConfirmationPolicy, ToolDefinition, ToolRiskLevel,
};

use super::super::schema::{
    boolean_field, enum_field, number_field, object_schema, string_array_field, string_field, tool,
    tool_with_policy, workflow_steps_field,
};

pub(super) fn automation_tools() -> Vec<ToolDefinition> {
    vec![
        tool(
            "snippet.create",
            "创建脚本片段",
            "创建一个可复用命令片段；只保存内容，不会自动写入或执行到任何终端。",
            ToolCategory::Snippet,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("title", "片段标题。", true),
                string_field("command", "命令或脚本内容。", true),
                string_field("description", "可选说明。", false),
                string_array_field("tags", "标签。", false),
                enum_field(
                    "scope",
                    "适用范围，默认 any。",
                    false,
                    vec!["any", "local", "ssh"],
                ),
            ]),
        ),
        tool(
            "snippet.list",
            "列出脚本片段",
            "按关键词、作用域或标签搜索脚本片段。",
            ToolCategory::Snippet,
            ToolRiskLevel::Read,
            object_schema(vec![
                string_field("query", "搜索关键词。", false),
                enum_field("scope", "适用范围。", false, vec!["any", "local", "ssh"]),
                string_field("tag", "标签过滤。", false),
            ]),
        ),
        tool(
            "snippet.update",
            "更新脚本片段",
            "更新可复用命令片段；只保存内容，不会自动执行。",
            ToolCategory::Snippet,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "片段 id。", true),
                string_field("title", "片段标题。", true),
                string_field("command", "命令或脚本内容。", true),
                string_field("description", "可选说明。", false),
                string_array_field("tags", "标签。", false),
                enum_field("scope", "适用范围。", false, vec!["any", "local", "ssh"]),
                number_field("sortOrder", "列表排序字段。", true),
            ]),
        ),
        tool_with_policy(
            "snippet.delete",
            "删除脚本片段",
            "删除可复用命令片段。",
            ToolCategory::Snippet,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("snippetId", "片段 id。", true)]),
        ),
        tool(
            "workflow.create",
            "创建命令工作流",
            "创建一个可复用多步骤命令工作流；只保存步骤，不会自动写入或执行到任何终端。",
            ToolCategory::Workflow,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("title", "工作流标题。", true),
                string_field("description", "可选说明。", false),
                string_array_field("tags", "标签。", false),
                enum_field(
                    "scope",
                    "默认适用范围，默认 any。",
                    false,
                    vec!["any", "local", "ssh"],
                ),
                workflow_steps_field(),
            ]),
        ),
        tool(
            "workflow.list",
            "列出命令工作流",
            "按关键词、作用域或标签搜索命令工作流。",
            ToolCategory::Workflow,
            ToolRiskLevel::Read,
            object_schema(vec![
                string_field("query", "搜索关键词。", false),
                enum_field(
                    "scope",
                    "默认适用范围。",
                    false,
                    vec!["any", "local", "ssh"],
                ),
                string_field("tag", "标签过滤。", false),
            ]),
        ),
        tool(
            "workflow.update",
            "更新命令工作流",
            "更新可复用多步骤命令工作流；只保存步骤，不会自动执行。",
            ToolCategory::Workflow,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "工作流 id。", true),
                string_field("title", "工作流标题。", true),
                string_field("description", "可选说明。", false),
                string_array_field("tags", "标签。", false),
                enum_field(
                    "scope",
                    "默认适用范围。",
                    false,
                    vec!["any", "local", "ssh"],
                ),
                number_field("sortOrder", "列表排序字段。", true),
                workflow_steps_field(),
            ]),
        ),
        tool_with_policy(
            "workflow.delete",
            "删除命令工作流",
            "删除可复用多步骤命令工作流。",
            ToolCategory::Workflow,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("workflowId", "工作流 id。", true)]),
        ),
        tool(
            "history.search",
            "搜索命令历史",
            "读取本地命令历史摘要，供 AI 理解最近操作和复用命令；不会执行任何命令。",
            ToolCategory::History,
            ToolRiskLevel::Read,
            object_schema(vec![
                string_field("query", "搜索关键词。", false),
                enum_field("target", "目标类型。", false, vec!["local", "ssh"]),
                enum_field(
                    "source",
                    "命令来源。",
                    false,
                    vec!["user", "ai", "snippet", "broadcast", "tool"],
                ),
                string_field("paneId", "前端 pane id。", false),
                string_field("remoteHostId", "SSH 主机 id。", false),
                string_field("sessionId", "终端 session id。", false),
                number_field("limit", "返回数量上限。", false),
            ]),
        ),
        tool(
            "history.record",
            "记录命令历史",
            "把一条命令写入本地命令历史；疑似密钥、密码或 token 的命令会被服务跳过。",
            ToolCategory::History,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("command", "命令内容。", true),
                enum_field(
                    "source",
                    "命令来源。",
                    false,
                    vec!["user", "ai", "snippet", "workflow", "broadcast", "tool"],
                ),
                enum_field("target", "目标类型。", false, vec!["local", "ssh"]),
                boolean_field("record", "当前会话是否允许记录历史。", false),
                string_field("sessionId", "终端 session id。", false),
                string_field("paneId", "前端 pane id。", false),
                string_field("tabId", "前端 tab id。", false),
                string_field("profileId", "本地 profile id。", false),
                string_field("remoteHostId", "SSH 主机 id。", false),
                string_field("cwd", "命令执行时工作目录。", false),
                string_field("shell", "命令执行时 shell。", false),
            ]),
        ),
        tool_with_policy(
            "history.delete",
            "删除命令历史",
            "删除一条本地命令历史记录。",
            ToolCategory::History,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("entryId", "命令历史 id。", true)]),
        ),
        tool_with_policy(
            "history.clear",
            "清空命令历史",
            "清空本地命令历史记录。",
            ToolCategory::History,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Full,
            true,
            true,
            object_schema(vec![]),
        ),
        tool(
            "diagnostics.runtime_health",
            "读取运行体检",
            "读取当前 Kerminal 进程、本机资源和本地数据目录的脱敏运行体检摘要。",
            ToolCategory::Diagnostics,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "diagnostics.create_bundle",
            "生成诊断包",
            "生成本地脱敏 JSON 诊断包；不会上传或分享文件，只返回生成摘要和路径。",
            ToolCategory::Diagnostics,
            ToolRiskLevel::Write,
            object_schema(vec![]),
        ),
        tool_with_policy(
            "workflow.run",
            "执行工作流",
            "执行多步骤 snippet/workflow。当前只登记 schema，等待 workflow 切片启用。",
            ToolCategory::Workflow,
            ToolRiskLevel::Batch,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Full,
            false,
            false,
            object_schema(vec![string_field("workflowId", "工作流 id。", true)]),
        ),
    ]
}
