//! 基础、设置、Provider 和 profile 工具目录。
//!
//! @author kongweiguang

use crate::models::tool_registry::{
    ToolAuditPolicy, ToolCategory, ToolConfirmationPolicy, ToolDefinition, ToolRiskLevel,
};

use super::super::schema::{
    boolean_field, enum_field, number_field, object_schema, string_array_field, string_field,
    string_record_field, tool, tool_with_policy,
};

pub(super) fn foundation_tools() -> Vec<ToolDefinition> {
    vec![
        tool(
            "terminal.create",
            "新建终端",
            "创建一个本地终端 tab；真实 PTY 会话由客户端 pane 初始化并绑定输出通道。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![
                number_field("cols", "初始列数。", true),
                number_field("rows", "初始行数。", true),
                string_field("title", "可选 tab 标题。", false),
                string_field("shell", "可选 shell 或命令路径。", false),
                string_array_field("args", "可选启动参数。", false),
                string_field("cwd", "可选工作目录。", false),
                string_record_field("env", "可选会话级环境变量覆盖。", false),
            ]),
        ),
        tool(
            "terminal.write",
            "写入终端",
            "向指定终端 session 写入输入数据。高风险命令会在 dispatch 阶段再次确认。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("sessionId", "终端 session id。", true),
                string_field("data", "写入终端的原始输入。", true),
            ]),
        ),
        tool(
            "terminal.resolve_current",
            "解析当前终端",
            "按当前 paneId 或已知 sessionId 解析可写终端目标，返回稳定 sessionId、paneId、tabId 和 target metadata，供 agent 后续调用 terminal.write/resize/log 工具。",
            ToolCategory::Terminal,
            ToolRiskLevel::Read,
            object_schema(vec![
                string_field("paneId", "可选当前 pane id；已知当前 UI pane 时优先传入。", false),
                string_field("sessionId", "可选终端 session id；用于和 paneId 交叉校验。", false),
                string_field("tabId", "可选当前 active tab id；用于和 pane metadata 交叉校验。", false),
                string_field("targetRef", "可选目标引用；用于和后端签发的 targetRef 交叉校验。", false),
                enum_field(
                    "targetKind",
                    "可选目标类型；用于和 pane metadata 交叉校验。",
                    false,
                    vec!["local", "ssh", "telnet", "serial", "dockerContainer"],
                ),
                string_field(
                    "remoteHostId",
                    "可选远程主机 id；SSH pane 可用来确认没有跨主机误写。",
                    false,
                ),
            ]),
        ),
        tool(
            "terminal.resize",
            "调整终端尺寸",
            "同步终端 pane 的 rows/cols 到后端 PTY 或 SSH 会话。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("sessionId", "终端 session id。", true),
                number_field("cols", "目标列数。", true),
                number_field("rows", "目标行数。", true),
            ]),
        ),
        tool(
            "terminal.list",
            "列出终端会话",
            "读取当前运行时本地终端会话摘要。",
            ToolCategory::Terminal,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool_with_policy(
            "terminal.close",
            "关闭终端会话",
            "关闭并移除指定本地终端会话。",
            ToolCategory::Terminal,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("sessionId", "终端 session id。", true)]),
        ),
        tool(
            "terminal.log.start",
            "开始终端日志",
            "开始把指定终端 session 的新输出写入本地日志文件。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![string_field("sessionId", "终端 session id。", true)]),
        ),
        tool(
            "terminal.log.stop",
            "停止终端日志",
            "停止指定终端 session 的日志记录并返回日志路径摘要。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![string_field("sessionId", "终端 session id。", true)]),
        ),
        tool(
            "terminal.log.state",
            "读取终端日志状态",
            "读取指定终端 session 当前日志记录状态。",
            ToolCategory::Terminal,
            ToolRiskLevel::Read,
            object_schema(vec![string_field("sessionId", "终端 session id。", true)]),
        ),
        tool(
            "workspace.split_pane",
            "分割当前分屏",
            "按水平或垂直方向拆分当前聚焦 pane。",
            ToolCategory::Workspace,
            ToolRiskLevel::Write,
            object_schema(vec![enum_field(
                "direction",
                "分屏方向。",
                true,
                vec!["horizontal", "vertical"],
            )]),
        ),
        tool(
            "workspace.focus_tab",
            "切换终端 tab",
            "把当前工作区焦点切换到指定终端 tab。",
            ToolCategory::Workspace,
            ToolRiskLevel::Write,
            object_schema(vec![string_field("tabId", "目标终端 tab id。", true)]),
        ),
        tool(
            "workspace.open_tool",
            "打开工具面板",
            "把右侧工具区切换到指定工具面板。",
            ToolCategory::Workspace,
            ToolRiskLevel::Write,
            object_schema(vec![enum_field(
                "toolId",
                "目标右侧工具面板。",
                true,
                vec![
                    "ai", "system", "sftp", "ports", "snippets", "logs", "settings",
                ],
            )]),
        ),
        tool(
            "settings.update_theme",
            "更新主题",
            "修改应用主题模式，支持深色、浅色和跟随系统。",
            ToolCategory::Settings,
            ToolRiskLevel::Write,
            object_schema(vec![enum_field(
                "themeMode",
                "主题模式。",
                true,
                vec!["dark", "light", "system"],
            )]),
        ),
        tool(
            "settings.update_terminal_appearance",
            "更新终端外观",
            "局部更新终端字体、字号、行高、光标闪烁和滚屏缓冲设置。",
            ToolCategory::Settings,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("fontFamily", "终端字体族。", false),
                number_field("fontSize", "终端字号，单位 px。", false),
                number_field("lineHeight", "终端行高倍率。", false),
                boolean_field("cursorBlink", "光标是否闪烁。", false),
                number_field("scrollback", "滚屏缓冲行数。", false),
            ]),
        ),
        tool(
            "settings.get",
            "读取设置",
            "读取当前应用主题、终端外观、快捷键和 AI 安全策略设置。",
            ToolCategory::Settings,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool_with_policy(
            "settings.update_ai_security",
            "更新 AI 安全策略",
            "局部更新 AI 上下文、确认策略、远程确认和破坏性工具开关。",
            ToolCategory::Settings,
            ToolRiskLevel::Write,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Full,
            true,
            true,
            object_schema(vec![
                number_field(
                    "contextMaxOutputBytes",
                    "AI 上下文最多读取的最近输出字节数。",
                    false,
                ),
                boolean_field(
                    "includeCommandHistory",
                    "是否允许 AI 上下文包含命令历史。",
                    false,
                ),
                boolean_field(
                    "requireRemoteApproval",
                    "远程 SSH/SFTP/服务器信息工具是否默认确认。",
                    false,
                ),
                boolean_field(
                    "allowDestructiveTools",
                    "是否允许破坏性工具进入可执行策略。",
                    false,
                ),
                enum_field(
                    "commandApprovalPolicy",
                    "AI 工具调用确认策略。",
                    false,
                    vec!["always", "risky", "relaxed"],
                ),
                number_field("commandTimeoutSeconds", "AI 发起命令默认超时秒数。", false),
                number_field("terminalTailLines", "终端最近输出显示行数。", false),
                string_field(
                    "customInstructions",
                    "用户自定义 AI 系统偏好，不存放密钥。",
                    false,
                ),
            ]),
        ),
        tool(
            "llm_provider.list",
            "列出模型 Provider",
            "读取全部 LLM Provider 配置摘要，不返回 API key 明文。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "llm_provider.create",
            "创建模型 Provider",
            "新增 LLM Provider 配置；API key 只短暂传入并写入本地凭据存储。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("name", "Provider 名称。", true),
                enum_field(
                    "kind",
                    "Provider 类型。",
                    true,
                    vec!["openAiResponses", "openAiChat", "anthropic"],
                ),
                string_field("baseUrl", "Provider API base URL。", true),
                string_field("model", "默认模型名称。", true),
                string_array_field("modelList", "可选模型列表。", false),
                number_field("temperature", "默认 temperature。", false),
                enum_field(
                    "contextStrategy",
                    "AI 上下文读取策略。",
                    false,
                    vec!["minimal", "currentTerminal", "currentWorkspace"],
                ),
                number_field("contextWindowTokens", "模型上下文窗口 tokens。", false),
                enum_field(
                    "reasoningEffort",
                    "推理强度配置。",
                    false,
                    vec!["modelDefault", "minimal", "low", "medium", "high"],
                ),
                number_field("maxRetries", "临时错误最大重试次数。", false),
                string_field("userAgent", "可选 User-Agent。", false),
                string_field("httpProxy", "可选 HTTP 代理地址。", false),
                boolean_field("enabled", "是否启用。", false),
                boolean_field("isDefault", "是否设为默认 Provider。", false),
                string_field("apiKey", "可选 API key 明文，审计摘要会脱敏。", false),
            ]),
        ),
        tool(
            "llm_provider.update",
            "更新模型 Provider",
            "更新 LLM Provider 配置；新 API key 只短暂传入并写入本地凭据存储。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "Provider id。", true),
                string_field("name", "Provider 名称。", true),
                enum_field(
                    "kind",
                    "Provider 类型。",
                    true,
                    vec!["openAiResponses", "openAiChat", "anthropic"],
                ),
                string_field("baseUrl", "Provider API base URL。", true),
                string_field("model", "默认模型名称。", true),
                string_array_field("modelList", "可选模型列表。", false),
                number_field("temperature", "默认 temperature。", false),
                enum_field(
                    "contextStrategy",
                    "AI 上下文读取策略。",
                    false,
                    vec!["minimal", "currentTerminal", "currentWorkspace"],
                ),
                number_field("contextWindowTokens", "模型上下文窗口 tokens。", false),
                enum_field(
                    "reasoningEffort",
                    "推理强度配置。",
                    false,
                    vec!["modelDefault", "minimal", "low", "medium", "high"],
                ),
                number_field("maxRetries", "临时错误最大重试次数。", false),
                string_field("userAgent", "可选 User-Agent。", false),
                string_field("httpProxy", "可选 HTTP 代理地址。", false),
                boolean_field("enabled", "是否启用。", false),
                boolean_field("isDefault", "是否设为默认 Provider。", false),
                string_field("apiKey", "可选新 API key 明文，审计摘要会脱敏。", false),
                boolean_field("clearApiKey", "是否清除已保存 API key。", false),
            ]),
        ),
        tool_with_policy(
            "llm_provider.delete",
            "删除模型 Provider",
            "删除 LLM Provider 配置并尽力清理对应凭据。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("id", "Provider id。", true)]),
        ),
        tool(
            "llm_provider.test",
            "测试模型 Provider",
            "对 LLM Provider 做本地 Rig dry validation，不发送真实 LLM 请求。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Read,
            object_schema(vec![string_field("id", "Provider id。", true)]),
        ),
        tool(
            "profile.create",
            "创建终端配置",
            "创建本地 terminal profile，包括 shell、启动参数、工作目录和环境变量。",
            ToolCategory::Profile,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("name", "配置名称。", true),
                string_field("shell", "shell 或命令路径。", true),
                string_array_field("args", "启动参数。", false),
                string_field("cwd", "工作目录。", false),
                string_record_field("env", "profile 级环境变量覆盖。", false),
                boolean_field("setDefault", "创建后是否设为默认 profile。", false),
            ]),
        ),
        tool(
            "profile.list",
            "列出终端配置",
            "读取本地 terminal profile 列表。",
            ToolCategory::Profile,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "profile.detect_shells",
            "探测可用 Shell",
            "探测当前主机可用 shell 候选，供创建本地终端配置使用。",
            ToolCategory::Profile,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "profile.update",
            "更新终端配置",
            "更新本地 terminal profile，包括 shell、启动参数、工作目录和环境变量。",
            ToolCategory::Profile,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "Profile id。", true),
                string_field("name", "配置名称。", true),
                string_field("shell", "shell 或命令路径。", true),
                string_array_field("args", "启动参数。", false),
                string_field("cwd", "工作目录。", false),
                string_record_field("env", "profile 级环境变量覆盖。", false),
                boolean_field("setDefault", "是否设为默认 profile。", false),
                number_field("sortOrder", "列表排序字段。", true),
            ]),
        ),
        tool_with_policy(
            "profile.delete",
            "删除终端配置",
            "删除本地 terminal profile；至少会保留一个本地 profile。",
            ToolCategory::Profile,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("profileId", "Profile id。", true)]),
        ),
    ]
}
