//! 远程主机、SSH 和连接工具目录。
//!
//! @author kongweiguang

use crate::models::tool_registry::{
    ToolAuditPolicy, ToolCategory, ToolConfirmationPolicy, ToolDefinition, ToolRiskLevel,
};

use super::super::schema::{
    boolean_field, enum_field, number_field, object_schema, string_array_field, string_field, tool,
    tool_with_policy,
};

pub(super) fn remote_tools() -> Vec<ToolDefinition> {
    vec![
        tool(
            "remote_host.create",
            "创建远程主机",
            "新增 SSH 主机配置；SSH 密码或内联私钥会按明文保存到主机记录。密码认证传 credentialSecret 或 password；密钥认证传 credentialRef 作为私钥路径，或传 credentialSecret/privateKey 作为内联私钥内容；不接受 credential: 凭据引用。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field(
                    "groupId",
                    "可选主机分组 id；如果只知道分组名称，优先使用 groupName。",
                    false,
                ),
                string_field(
                    "groupName",
                    "可选主机分组名称；工具会自动匹配已有分组，不存在时自动创建。",
                    false,
                ),
                string_field("name", "主机名称。", true),
                string_field("host", "主机名或 IP。", true),
                number_field("port", "SSH 端口。", true),
                string_field("username", "SSH 用户名。", true),
                enum_field(
                    "authType",
                    "SSH 认证方式，默认使用 SSH Agent。",
                    false,
                    vec!["agent", "key", "password"],
                ),
                string_field(
                    "credentialRef",
                    "可选私钥路径，仅 authType=key 时使用；不要传 credential: 引用。",
                    false,
                ),
                string_field(
                    "credentialSecret",
                    "可选 SSH 密码或内联私钥内容；会随主机记录明文保存，审计摘要会脱敏。",
                    false,
                ),
                string_field(
                    "password",
                    "可选 SSH 密码，等价于 password 认证下的 credentialSecret；会明文保存到主机记录。",
                    false,
                ),
                string_field(
                    "privateKey",
                    "可选 OpenSSH 私钥内容，等价于密钥认证下的 credentialSecret；会明文保存到主机记录。",
                    false,
                ),
                string_array_field("tags", "主机标签。", false),
                boolean_field("production", "是否生产主机。", false),
            ]),
        ),
        tool(
            "remote_host.ensure",
            "确保远程主机存在",
            "按分组名称、主机地址、端口、用户名和名称查找或创建 SSH 主机配置；返回稳定 hostId/groupId，适合自然语言创建主机后继续连接。SSH 密码或内联私钥会按明文保存到主机记录；如果命中已有主机且本次提供了新凭据，会更新该主机凭据。不接受 credential: 凭据引用。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field(
                    "groupId",
                    "可选主机分组 id；如果只知道分组名称，优先使用 groupName。",
                    false,
                ),
                string_field(
                    "groupName",
                    "可选主机分组名称；工具会自动匹配已有分组，不存在时自动创建。",
                    false,
                ),
                string_field("name", "主机名称；通常可用主机名或 IP。", true),
                string_field("host", "主机名或 IP。", true),
                number_field("port", "SSH 端口。", true),
                string_field("username", "SSH 用户名。", true),
                enum_field(
                    "authType",
                    "SSH 认证方式，默认使用 SSH Agent。",
                    false,
                    vec!["agent", "key", "password"],
                ),
                string_field(
                    "credentialRef",
                    "可选私钥路径，仅 authType=key 时使用；不要传 credential: 引用。",
                    false,
                ),
                string_field(
                    "credentialSecret",
                    "可选 SSH 密码或内联私钥内容；会随主机记录明文保存，审计摘要会脱敏。",
                    false,
                ),
                string_field(
                    "password",
                    "可选 SSH 密码，等价于 password 认证下的 credentialSecret；会明文保存到主机记录。",
                    false,
                ),
                string_field(
                    "privateKey",
                    "可选 OpenSSH 私钥内容，等价于密钥认证下的 credentialSecret；会明文保存到主机记录。",
                    false,
                ),
                string_array_field("tags", "主机标签。", false),
                boolean_field("production", "是否生产主机。", false),
            ]),
        ),
        tool(
            "remote_host.last_used",
            "读取最近使用的 SSH 主机",
            "从 SSH 命令历史中解析最近仍存在的远程主机，返回稳定 hostId/groupId 和 remoteHost 实体，适合 agent 在缺少 groupId/hostId 时先自动补齐目标。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Read,
            object_schema(vec![enum_field(
                "target",
                "历史目标类型；当前仅支持 ssh。",
                false,
                vec!["ssh"],
            )]),
        ),
        tool(
            "remote_host.group_list",
            "列出远程主机分组",
            "读取远程主机分组列表。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "remote_host.tree",
            "读取远程主机树",
            "读取远程主机分组及主机树。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "remote_host.group_create",
            "创建远程主机分组",
            "新增远程主机分组。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Write,
            object_schema(vec![string_field("name", "分组名称。", true)]),
        ),
        tool(
            "remote_host.group_update",
            "更新远程主机分组",
            "更新远程主机分组名称和排序字段。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "分组 id。", true),
                string_field("name", "分组名称。", true),
                number_field("sortOrder", "排序字段。", true),
            ]),
        ),
        tool_with_policy(
            "remote_host.group_delete",
            "删除远程主机分组",
            "删除远程主机分组；组内主机会移动到默认分组。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("groupId", "分组 id。", true)]),
        ),
        tool(
            "remote_host.update",
            "更新远程主机",
            "更新 SSH 主机配置；SSH 密码或内联私钥会按明文保存到主机记录。密码认证传 credentialSecret 或 password；密钥认证传 credentialRef 作为私钥路径，或传 credentialSecret/privateKey 作为内联私钥内容；不接受 credential: 凭据引用。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("id", "远程主机 id。", true),
                string_field(
                    "groupId",
                    "可选主机分组 id；如果只知道分组名称，优先使用 groupName。",
                    false,
                ),
                string_field(
                    "groupName",
                    "可选主机分组名称；工具会自动匹配已有分组，不存在时自动创建。",
                    false,
                ),
                string_field("name", "主机名称。", true),
                string_field("host", "主机名或 IP。", true),
                number_field("port", "SSH 端口。", true),
                string_field("username", "SSH 用户名。", true),
                enum_field(
                    "authType",
                    "SSH 认证方式，默认使用 SSH Agent。",
                    false,
                    vec!["agent", "key", "password"],
                ),
                string_field(
                    "credentialRef",
                    "可选私钥路径，仅 authType=key 时使用；不要传 credential: 引用。",
                    false,
                ),
                string_field(
                    "credentialSecret",
                    "可选 SSH 密码或内联私钥内容；会随主机记录明文保存，审计摘要会脱敏。",
                    false,
                ),
                string_field(
                    "password",
                    "可选 SSH 密码，等价于 password 认证下的 credentialSecret；会明文保存到主机记录。",
                    false,
                ),
                string_field(
                    "privateKey",
                    "可选 OpenSSH 私钥内容，等价于密钥认证下的 credentialSecret；会明文保存到主机记录。",
                    false,
                ),
                string_array_field("tags", "主机标签。", false),
                boolean_field("production", "是否生产主机。", false),
                number_field("sortOrder", "列表排序字段。", true),
            ]),
        ),
        tool_with_policy(
            "remote_host.delete",
            "删除远程主机",
            "删除已保存 SSH 主机配置。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("hostId", "远程主机 id。", true)]),
        ),
        tool(
            "ssh.connect",
            "打开 SSH 终端",
            "基于已保存主机配置创建 SSH 终端会话。",
            ToolCategory::Ssh,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                number_field("cols", "初始列数。", true),
                number_field("rows", "初始行数。", true),
            ]),
        ),
        tool(
            "ssh.ensure_connected",
            "确保 SSH 终端打开",
            "按 hostId 或主机选择条件解析已保存 SSH 主机，并请求客户端打开 SSH 终端；适合 remote_host.ensure 后继续连接。",
            ToolCategory::Ssh,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "可选远程主机 id；已知时优先传入。", false),
                string_field("groupId", "可选主机分组 id。", false),
                string_field("groupName", "可选主机分组名称。", false),
                string_field("name", "可选主机名称。", false),
                string_field("host", "可选主机名或 IP。", false),
                string_field("username", "可选 SSH 用户名。", false),
                number_field("port", "可选 SSH 端口。", false),
                number_field("cols", "初始列数。", true),
                number_field("rows", "初始行数。", true),
            ]),
        ),
        tool(
            "ssh.command",
            "执行远程命令",
            "在已保存 SSH 主机上执行非交互命令；执行前必须确认，高风险命令会升级为破坏性确认。",
            ToolCategory::Ssh,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("command", "远程 shell 命令或脚本片段。", true),
                string_field(
                    "proxyUrl",
                    "可选代理 URL；用于本次 AI/工具远程命令的临时环境变量注入，不写入远端 profile。",
                    false,
                ),
                enum_field(
                    "proxyProtocol",
                    "proxyUrl 的协议；缺省时根据 URL 推断。",
                    false,
                    vec!["http", "socks5"],
                ),
                number_field("timeoutSeconds", "执行超时时间，单位秒。", false),
                number_field(
                    "maxOutputBytes",
                    "stdout/stderr 各自最多保留字节数。",
                    false,
                ),
            ]),
        ),
        tool(
            "ssh.command_on_resolved_host",
            "解析目标后执行远程命令",
            "按 hostId 或主机选择条件解析已保存 SSH 主机，并在解析出的主机上执行非交互命令；适合自然语言只给出分组、主机或用户名时继续完成远程操作。",
            ToolCategory::Ssh,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "可选远程主机 id；已知时优先传入。", false),
                string_field("groupId", "可选主机分组 id。", false),
                string_field("groupName", "可选主机分组名称。", false),
                string_field("name", "可选主机名称。", false),
                string_field("host", "可选主机名或 IP。", false),
                string_field("username", "可选 SSH 用户名。", false),
                number_field("port", "可选 SSH 端口。", false),
                string_field("command", "远程 shell 命令或脚本片段。", true),
                string_field(
                    "proxyUrl",
                    "可选代理 URL；用于本次 AI/工具远程命令的临时环境变量注入，不写入远端 profile。",
                    false,
                ),
                enum_field(
                    "proxyProtocol",
                    "proxyUrl 的协议；缺省时根据 URL 推断。",
                    false,
                    vec!["http", "socks5"],
                ),
                number_field("timeoutSeconds", "执行超时时间，单位秒。", false),
                number_field(
                    "maxOutputBytes",
                    "stdout/stderr 各自最多保留字节数。",
                    false,
                ),
            ]),
        ),
        tool(
            "connection.rdp_open",
            "打开 RDP 连接",
            "生成临时 .rdp 文件并请求系统 RDP 客户端启动；密码只用于本次启动且审计摘要会脱敏。",
            ToolCategory::Connection,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("name", "连接名称。", true),
                string_field("host", "RDP 主机地址。", true),
                number_field("port", "RDP 端口。", true),
                string_field("username", "可选用户名。", false),
                string_field("password", "可选密码，审计摘要会脱敏。", false),
                boolean_field("fullscreen", "是否全屏启动。", false),
                number_field("desktopWidth", "非全屏窗口宽度。", false),
                number_field("desktopHeight", "非全屏窗口高度。", false),
                string_field("note", "备注。", false),
            ]),
        ),
    ]
}
