//! 内置工具注册表目录。
//!
//! @author kongweiguang

use crate::models::tool_registry::{
    ToolAuditPolicy, ToolCategory, ToolConfirmationPolicy, ToolDefinition, ToolRiskLevel,
};

use super::schema::{
    boolean_field, enum_field, number_field, object_schema, string_array_field, string_field,
    string_record_field, tool, tool_with_policy, workflow_steps_field,
};

pub(super) fn registered_tools() -> Vec<ToolDefinition> {
    vec![
        tool(
            "terminal.create",
            "新建终端",
            "创建一个本地终端 tab；真实 PTY 会话由客户端 pane 初始化并绑定输出通道。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![
                number_field("cols", "初始列数。", true),
                number_field("rows", "初始行数。", true),
                string_field("title", "可选 tab 标题。", false),
                string_field("shell", "可选 shell 或命令路径。", false),
                string_array_field("args", "可选启动参数。", false),
                string_field("cwd", "可选工作目录。", false),
                string_record_field("env", "可选会话级环境变量覆盖。", false),
            ]),
        ),
        tool(
            "terminal.write",
            "写入终端",
            "向指定终端 session 写入输入数据。高风险命令会在 dispatch 阶段再次确认。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("sessionId", "终端 session id。", true),
                string_field("data", "写入终端的原始输入。", true),
            ]),
        ),
        tool(
            "terminal.resize",
            "调整终端尺寸",
            "同步终端 pane 的 rows/cols 到后端 PTY 或 SSH 会话。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("sessionId", "终端 session id。", true),
                number_field("cols", "目标列数。", true),
                number_field("rows", "目标行数。", true),
            ]),
        ),
        tool(
            "terminal.list",
            "列出终端会话",
            "读取当前运行时本地终端会话摘要。",
            ToolCategory::Terminal,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool_with_policy(
            "terminal.close",
            "关闭终端会话",
            "关闭并移除指定本地终端会话。",
            ToolCategory::Terminal,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("sessionId", "终端 session id。", true)]),
        ),
        tool(
            "terminal.log.start",
            "开始终端日志",
            "开始把指定终端 session 的新输出写入本地日志文件。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![string_field("sessionId", "终端 session id。", true)]),
        ),
        tool(
            "terminal.log.stop",
            "停止终端日志",
            "停止指定终端 session 的日志记录并返回日志路径摘要。",
            ToolCategory::Terminal,
            ToolRiskLevel::Write,
            object_schema(vec![string_field("sessionId", "终端 session id。", true)]),
        ),
        tool(
            "terminal.log.state",
            "读取终端日志状态",
            "读取指定终端 session 当前日志记录状态。",
            ToolCategory::Terminal,
            ToolRiskLevel::Read,
            object_schema(vec![string_field("sessionId", "终端 session id。", true)]),
        ),
        tool(
            "workspace.split_pane",
            "分割当前分屏",
            "按水平或垂直方向拆分当前聚焦 pane。",
            ToolCategory::Workspace,
            ToolRiskLevel::Write,
            object_schema(vec![enum_field(
                "direction",
                "分屏方向。",
                true,
                vec!["horizontal", "vertical"],
            )]),
        ),
        tool(
            "workspace.focus_tab",
            "切换终端 tab",
            "把当前工作区焦点切换到指定终端 tab。",
            ToolCategory::Workspace,
            ToolRiskLevel::Write,
            object_schema(vec![string_field("tabId", "目标终端 tab id。", true)]),
        ),
        tool(
            "workspace.open_tool",
            "打开工具面板",
            "把右侧工具区切换到指定工具面板。",
            ToolCategory::Workspace,
            ToolRiskLevel::Write,
            object_schema(vec![enum_field(
                "toolId",
                "目标右侧工具面板。",
                true,
                vec![
                    "ai", "system", "sftp", "ports", "snippets", "logs", "settings",
                ],
            )]),
        ),
        tool(
            "settings.update_theme",
            "更新主题",
            "修改应用主题模式，支持深色、浅色和跟随系统。",
            ToolCategory::Settings,
            ToolRiskLevel::Write,
            object_schema(vec![enum_field(
                "themeMode",
                "主题模式。",
                true,
                vec!["dark", "light", "system"],
            )]),
        ),
        tool(
            "settings.update_terminal_appearance",
            "更新终端外观",
            "局部更新终端字体、字号、行高、光标闪烁和滚屏缓冲设置。",
            ToolCategory::Settings,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("fontFamily", "终端字体族。", false),
                number_field("fontSize", "终端字号，单位 px。", false),
                number_field("lineHeight", "终端行高倍率。", false),
                boolean_field("cursorBlink", "光标是否闪烁。", false),
                number_field("scrollback", "滚屏缓冲行数。", false),
            ]),
        ),
        tool(
            "settings.get",
            "读取设置",
            "读取当前应用主题、终端外观、快捷键和 AI 安全策略设置。",
            ToolCategory::Settings,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool_with_policy(
            "settings.update_ai_security",
            "更新 AI 安全策略",
            "局部更新 AI 上下文、确认策略、远程确认和破坏性工具开关。",
            ToolCategory::Settings,
            ToolRiskLevel::Write,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Full,
            true,
            true,
            object_schema(vec![
                number_field(
                    "contextMaxOutputBytes",
                    "AI 上下文最多读取的最近输出字节数。",
                    false,
                ),
                boolean_field(
                    "includeCommandHistory",
                    "是否允许 AI 上下文包含命令历史。",
                    false,
                ),
                boolean_field(
                    "requireRemoteApproval",
                    "远程 SSH/SFTP/服务器信息工具是否默认确认。",
                    false,
                ),
                boolean_field(
                    "allowDestructiveTools",
                    "是否允许破坏性工具进入可执行策略。",
                    false,
                ),
                enum_field(
                    "commandApprovalPolicy",
                    "AI 工具调用确认策略。",
                    false,
                    vec!["always", "risky", "relaxed"],
                ),
                number_field("commandTimeoutSeconds", "AI 发起命令默认超时秒数。", false),
                number_field("terminalTailLines", "终端最近输出显示行数。", false),
                string_field(
                    "customInstructions",
                    "用户自定义 AI 系统偏好，不存放密钥。",
                    false,
                ),
            ]),
        ),
        tool(
            "llm_provider.list",
            "列出模型 Provider",
            "读取全部 LLM Provider 配置摘要，不返回 API key 明文。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "llm_provider.create",
            "创建模型 Provider",
            "新增 LLM Provider 配置；API key 只短暂传入并写入本地凭据存储。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("name", "Provider 名称。", true),
                enum_field(
                    "kind",
                    "Provider 类型。",
                    true,
                    vec!["openAiResponses", "openAiChat", "anthropic"],
                ),
                string_field("baseUrl", "Provider API base URL。", true),
                string_field("model", "默认模型名称。", true),
                string_array_field("modelList", "可选模型列表。", false),
                number_field("temperature", "默认 temperature。", false),
                enum_field(
                    "contextStrategy",
                    "AI 上下文读取策略。",
                    false,
                    vec!["minimal", "currentTerminal", "currentWorkspace"],
                ),
                number_field("contextWindowTokens", "模型上下文窗口 tokens。", false),
                enum_field(
                    "reasoningEffort",
                    "推理强度配置。",
                    false,
                    vec!["modelDefault", "minimal", "low", "medium", "high"],
                ),
                number_field("maxRetries", "临时错误最大重试次数。", false),
                string_field("userAgent", "可选 User-Agent。", false),
                string_field("httpProxy", "可选 HTTP 代理地址。", false),
                boolean_field("enabled", "是否启用。", false),
                boolean_field("isDefault", "是否设为默认 Provider。", false),
                string_field("apiKey", "可选 API key 明文，审计摘要会脱敏。", false),
            ]),
        ),
        tool(
            "llm_provider.update",
            "更新模型 Provider",
            "更新 LLM Provider 配置；新 API key 只短暂传入并写入本地凭据存储。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "Provider id。", true),
                string_field("name", "Provider 名称。", true),
                enum_field(
                    "kind",
                    "Provider 类型。",
                    true,
                    vec!["openAiResponses", "openAiChat", "anthropic"],
                ),
                string_field("baseUrl", "Provider API base URL。", true),
                string_field("model", "默认模型名称。", true),
                string_array_field("modelList", "可选模型列表。", false),
                number_field("temperature", "默认 temperature。", false),
                enum_field(
                    "contextStrategy",
                    "AI 上下文读取策略。",
                    false,
                    vec!["minimal", "currentTerminal", "currentWorkspace"],
                ),
                number_field("contextWindowTokens", "模型上下文窗口 tokens。", false),
                enum_field(
                    "reasoningEffort",
                    "推理强度配置。",
                    false,
                    vec!["modelDefault", "minimal", "low", "medium", "high"],
                ),
                number_field("maxRetries", "临时错误最大重试次数。", false),
                string_field("userAgent", "可选 User-Agent。", false),
                string_field("httpProxy", "可选 HTTP 代理地址。", false),
                boolean_field("enabled", "是否启用。", false),
                boolean_field("isDefault", "是否设为默认 Provider。", false),
                string_field("apiKey", "可选新 API key 明文，审计摘要会脱敏。", false),
                boolean_field("clearApiKey", "是否清除已保存 API key。", false),
            ]),
        ),
        tool_with_policy(
            "llm_provider.delete",
            "删除模型 Provider",
            "删除 LLM Provider 配置并尽力清理对应凭据。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("id", "Provider id。", true)]),
        ),
        tool(
            "llm_provider.test",
            "测试模型 Provider",
            "对 LLM Provider 做本地 Rig dry validation，不发送真实 LLM 请求。",
            ToolCategory::LlmProvider,
            ToolRiskLevel::Read,
            object_schema(vec![string_field("id", "Provider id。", true)]),
        ),
        tool(
            "profile.create",
            "创建终端配置",
            "创建本地 terminal profile，包括 shell、启动参数、工作目录和环境变量。",
            ToolCategory::Profile,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("name", "配置名称。", true),
                string_field("shell", "shell 或命令路径。", true),
                string_array_field("args", "启动参数。", false),
                string_field("cwd", "工作目录。", false),
                string_record_field("env", "profile 级环境变量覆盖。", false),
                boolean_field("setDefault", "创建后是否设为默认 profile。", false),
            ]),
        ),
        tool(
            "profile.list",
            "列出终端配置",
            "读取本地 terminal profile 列表。",
            ToolCategory::Profile,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "profile.detect_shells",
            "探测可用 Shell",
            "探测当前主机可用 shell 候选，供创建本地终端配置使用。",
            ToolCategory::Profile,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "profile.update",
            "更新终端配置",
            "更新本地 terminal profile，包括 shell、启动参数、工作目录和环境变量。",
            ToolCategory::Profile,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "Profile id。", true),
                string_field("name", "配置名称。", true),
                string_field("shell", "shell 或命令路径。", true),
                string_array_field("args", "启动参数。", false),
                string_field("cwd", "工作目录。", false),
                string_record_field("env", "profile 级环境变量覆盖。", false),
                boolean_field("setDefault", "是否设为默认 profile。", false),
                number_field("sortOrder", "列表排序字段。", true),
            ]),
        ),
        tool_with_policy(
            "profile.delete",
            "删除终端配置",
            "删除本地 terminal profile；至少会保留一个本地 profile。",
            ToolCategory::Profile,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("profileId", "Profile id。", true)]),
        ),
        tool(
            "remote_host.create",
            "创建远程主机",
            "新增 SSH 主机配置；凭据只能传递 credential ref，不能传递明文密钥。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("groupId", "可选主机分组 id；缺省时保存到默认分组。", false),
                string_field("name", "主机名称。", true),
                string_field("host", "主机名或 IP。", true),
                number_field("port", "SSH 端口。", true),
                string_field("username", "SSH 用户名。", true),
                enum_field(
                    "authType",
                    "SSH 认证方式，默认使用 SSH Agent。",
                    false,
                    vec!["agent", "key", "password"],
                ),
                string_field("credentialRef", "凭据引用。", false),
                string_array_field("tags", "主机标签。", false),
                boolean_field("production", "是否生产主机。", false),
            ]),
        ),
        tool(
            "remote_host.group_list",
            "列出远程主机分组",
            "读取远程主机分组列表。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "remote_host.tree",
            "读取远程主机树",
            "读取远程主机分组及主机树。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "remote_host.group_create",
            "创建远程主机分组",
            "新增远程主机分组。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Write,
            object_schema(vec![string_field("name", "分组名称。", true)]),
        ),
        tool(
            "remote_host.group_update",
            "更新远程主机分组",
            "更新远程主机分组名称和排序字段。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "分组 id。", true),
                string_field("name", "分组名称。", true),
                number_field("sortOrder", "排序字段。", true),
            ]),
        ),
        tool_with_policy(
            "remote_host.group_delete",
            "删除远程主机分组",
            "删除远程主机分组；组内主机会移动到默认分组。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("groupId", "分组 id。", true)]),
        ),
        tool(
            "remote_host.update",
            "更新远程主机",
            "更新 SSH 主机配置；凭据只能传递 credential ref，不能传递明文密钥。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("id", "远程主机 id。", true),
                string_field("groupId", "可选主机分组 id；缺省时保存到默认分组。", false),
                string_field("name", "主机名称。", true),
                string_field("host", "主机名或 IP。", true),
                number_field("port", "SSH 端口。", true),
                string_field("username", "SSH 用户名。", true),
                enum_field(
                    "authType",
                    "SSH 认证方式，默认使用 SSH Agent。",
                    false,
                    vec!["agent", "key", "password"],
                ),
                string_field("credentialRef", "凭据引用。", false),
                string_array_field("tags", "主机标签。", false),
                boolean_field("production", "是否生产主机。", false),
                number_field("sortOrder", "列表排序字段。", true),
            ]),
        ),
        tool_with_policy(
            "remote_host.delete",
            "删除远程主机",
            "删除已保存 SSH 主机配置。",
            ToolCategory::RemoteHost,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("hostId", "远程主机 id。", true)]),
        ),
        tool(
            "ssh.connect",
            "打开 SSH 终端",
            "基于已保存主机配置创建 SSH 终端会话。",
            ToolCategory::Ssh,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                number_field("cols", "初始列数。", true),
                number_field("rows", "初始行数。", true),
            ]),
        ),
        tool(
            "ssh.command",
            "执行远程命令",
            "在已保存 SSH 主机上执行非交互命令；执行前必须确认，高风险命令会升级为破坏性确认。",
            ToolCategory::Ssh,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("command", "远程 shell 命令或脚本片段。", true),
                number_field("timeoutSeconds", "执行超时时间，单位秒。", false),
                number_field(
                    "maxOutputBytes",
                    "stdout/stderr 各自最多保留字节数。",
                    false,
                ),
            ]),
        ),
        tool(
            "connection.rdp_open",
            "打开 RDP 连接",
            "生成临时 .rdp 文件并请求系统 RDP 客户端启动；密码只用于本次启动且审计摘要会脱敏。",
            ToolCategory::Connection,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("name", "连接名称。", true),
                string_field("host", "RDP 主机地址。", true),
                number_field("port", "RDP 端口。", true),
                string_field("username", "可选用户名。", false),
                string_field("password", "可选密码，审计摘要会脱敏。", false),
                boolean_field("fullscreen", "是否全屏启动。", false),
                number_field("desktopWidth", "非全屏窗口宽度。", false),
                number_field("desktopHeight", "非全屏窗口高度。", false),
                string_field("note", "备注。", false),
            ]),
        ),
        tool(
            "sftp.list",
            "列出远程目录",
            "读取当前 SSH 主机上的远程目录内容。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程目录路径。", true),
            ]),
        ),
        tool(
            "sftp.rename",
            "重命名远程路径",
            "重命名当前 SSH 主机上的远程文件或目录路径；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("fromPath", "原远程路径。", true),
                string_field("toPath", "新远程路径。", true),
            ]),
        ),
        tool(
            "sftp.move",
            "移动远程路径",
            "移动当前 SSH 主机上的远程文件或目录路径；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("fromPath", "原远程路径。", true),
                string_field("toPath", "目标远程路径。", true),
            ]),
        ),
        tool(
            "sftp.preview",
            "预览远程文件",
            "读取当前 SSH 主机上的远程文本文件预览；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程文件路径。", true),
                number_field("maxBytes", "最多读取字节数。", false),
            ]),
        ),
        tool(
            "sftp.download",
            "下载远程文件",
            "从当前 SSH 主机下载远程文件到本地路径；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("remotePath", "远程文件路径。", true),
                string_field("localPath", "本地保存路径。", true),
            ]),
        ),
        tool(
            "sftp.upload",
            "上传本地文件",
            "上传本地文件到当前 SSH 主机的远程路径；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("localPath", "本地文件路径。", true),
                string_field("remotePath", "远程保存路径。", true),
            ]),
        ),
        tool_with_policy(
            "sftp.delete",
            "删除远程文件",
            "删除当前 SSH 主机上的远程文件或空目录；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Full,
            true,
            true,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程路径。", true),
                boolean_field("directory", "是否按空目录删除。", false),
            ]),
        ),
        tool(
            "sftp.create_directory",
            "创建远程目录",
            "在当前 SSH 主机上创建远程目录；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程目录路径。", true),
            ]),
        ),
        tool(
            "sftp.chmod",
            "修改远程权限",
            "修改当前 SSH 主机上的远程路径权限；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程路径。", true),
                string_field("mode", "八进制权限模式，例如 644 或 0755。", true),
            ]),
        ),
        tool(
            "sftp.upload_directory",
            "上传本地目录",
            "递归上传本地目录到当前 SSH 主机远程路径；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("localPath", "本地目录路径。", true),
                string_field("remotePath", "远程保存路径。", true),
            ]),
        ),
        tool(
            "sftp.download_directory",
            "下载远程目录",
            "递归下载当前 SSH 主机远程目录到本地路径；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("remotePath", "远程目录路径。", true),
                string_field("localPath", "本地保存路径。", true),
            ]),
        ),
        tool(
            "sftp.transfer.enqueue",
            "创建 SFTP 传输任务",
            "把上传或下载任务加入 SFTP 传输队列，并返回可取消、可查看进度的任务 id。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("remotePath", "远程路径。", true),
                string_field("localPath", "本地路径。", true),
                enum_field("direction", "传输方向。", true, vec!["upload", "download"]),
                enum_field("kind", "传输对象类型。", true, vec!["file", "directory"]),
            ]),
        ),
        tool(
            "sftp.transfer.list",
            "列出 SFTP 传输任务",
            "读取当前运行时 SFTP 传输队列、状态和进度摘要。",
            ToolCategory::Sftp,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "sftp.transfer.cancel",
            "取消 SFTP 传输任务",
            "请求取消指定 SFTP 传输任务；执行前必须确认。",
            ToolCategory::Sftp,
            ToolRiskLevel::Remote,
            object_schema(vec![string_field("transferId", "SFTP 传输任务 id。", true)]),
        ),
        tool(
            "sftp.transfer.clear_completed",
            "清理已结束 SFTP 任务",
            "从运行时队列中清理已成功、已失败或已取消的 SFTP 传输任务。",
            ToolCategory::Sftp,
            ToolRiskLevel::Write,
            object_schema(vec![]),
        ),
        tool(
            "server_info.snapshot",
            "读取服务器信息",
            "读取 SSH 主机 CPU、内存、磁盘、网络和运行时间摘要。",
            ToolCategory::ServerInfo,
            ToolRiskLevel::Remote,
            object_schema(vec![string_field("hostId", "远程主机 id。", true)]),
        ),
        tool(
            "port_forward.create",
            "创建端口转发",
            "创建 local、remote 或 dynamic SSH 端口转发。",
            ToolCategory::PortForward,
            ToolRiskLevel::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("name", "用户可见转发名称。", false),
                enum_field(
                    "kind",
                    "转发类型。",
                    true,
                    vec!["local", "remote", "dynamic"],
                ),
                string_field("bindHost", "监听地址，默认 127.0.0.1。", false),
                number_field(
                    "sourcePort",
                    "监听端口，本地/动态时是本机端口，远程时是远端监听端口。",
                    true,
                ),
                string_field("targetHost", "目标主机；dynamic 转发可为空。", false),
                number_field("targetPort", "目标端口；dynamic 转发可为空。", false),
            ]),
        ),
        tool(
            "port_forward.list",
            "列出端口转发",
            "读取当前运行时 SSH 端口转发会话摘要。",
            ToolCategory::PortForward,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "port_forward.close",
            "关闭端口转发",
            "关闭指定 SSH 端口转发会话；执行前必须确认。",
            ToolCategory::PortForward,
            ToolRiskLevel::Remote,
            object_schema(vec![string_field("forwardId", "端口转发会话 id。", true)]),
        ),
        tool(
            "snippet.create",
            "创建脚本片段",
            "创建一个可复用命令片段；只保存内容，不会自动写入或执行到任何终端。",
            ToolCategory::Snippet,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("title", "片段标题。", true),
                string_field("command", "命令或脚本内容。", true),
                string_field("description", "可选说明。", false),
                string_array_field("tags", "标签。", false),
                enum_field(
                    "scope",
                    "适用范围，默认 any。",
                    false,
                    vec!["any", "local", "ssh"],
                ),
            ]),
        ),
        tool(
            "snippet.list",
            "列出脚本片段",
            "按关键词、作用域或标签搜索脚本片段。",
            ToolCategory::Snippet,
            ToolRiskLevel::Read,
            object_schema(vec![
                string_field("query", "搜索关键词。", false),
                enum_field("scope", "适用范围。", false, vec!["any", "local", "ssh"]),
                string_field("tag", "标签过滤。", false),
            ]),
        ),
        tool(
            "snippet.update",
            "更新脚本片段",
            "更新可复用命令片段；只保存内容，不会自动执行。",
            ToolCategory::Snippet,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "片段 id。", true),
                string_field("title", "片段标题。", true),
                string_field("command", "命令或脚本内容。", true),
                string_field("description", "可选说明。", false),
                string_array_field("tags", "标签。", false),
                enum_field("scope", "适用范围。", false, vec!["any", "local", "ssh"]),
                number_field("sortOrder", "列表排序字段。", true),
            ]),
        ),
        tool_with_policy(
            "snippet.delete",
            "删除脚本片段",
            "删除可复用命令片段。",
            ToolCategory::Snippet,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("snippetId", "片段 id。", true)]),
        ),
        tool(
            "workflow.create",
            "创建命令工作流",
            "创建一个可复用多步骤命令工作流；只保存步骤，不会自动写入或执行到任何终端。",
            ToolCategory::Workflow,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("title", "工作流标题。", true),
                string_field("description", "可选说明。", false),
                string_array_field("tags", "标签。", false),
                enum_field(
                    "scope",
                    "默认适用范围，默认 any。",
                    false,
                    vec!["any", "local", "ssh"],
                ),
                workflow_steps_field(),
            ]),
        ),
        tool(
            "workflow.list",
            "列出命令工作流",
            "按关键词、作用域或标签搜索命令工作流。",
            ToolCategory::Workflow,
            ToolRiskLevel::Read,
            object_schema(vec![
                string_field("query", "搜索关键词。", false),
                enum_field(
                    "scope",
                    "默认适用范围。",
                    false,
                    vec!["any", "local", "ssh"],
                ),
                string_field("tag", "标签过滤。", false),
            ]),
        ),
        tool(
            "workflow.update",
            "更新命令工作流",
            "更新可复用多步骤命令工作流；只保存步骤，不会自动执行。",
            ToolCategory::Workflow,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("id", "工作流 id。", true),
                string_field("title", "工作流标题。", true),
                string_field("description", "可选说明。", false),
                string_array_field("tags", "标签。", false),
                enum_field(
                    "scope",
                    "默认适用范围。",
                    false,
                    vec!["any", "local", "ssh"],
                ),
                number_field("sortOrder", "列表排序字段。", true),
                workflow_steps_field(),
            ]),
        ),
        tool_with_policy(
            "workflow.delete",
            "删除命令工作流",
            "删除可复用多步骤命令工作流。",
            ToolCategory::Workflow,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("workflowId", "工作流 id。", true)]),
        ),
        tool(
            "history.search",
            "搜索命令历史",
            "读取本地命令历史摘要，供 AI 理解最近操作和复用命令；不会执行任何命令。",
            ToolCategory::History,
            ToolRiskLevel::Read,
            object_schema(vec![
                string_field("query", "搜索关键词。", false),
                enum_field("target", "目标类型。", false, vec!["local", "ssh"]),
                enum_field(
                    "source",
                    "命令来源。",
                    false,
                    vec!["user", "ai", "snippet", "broadcast", "tool"],
                ),
                string_field("paneId", "前端 pane id。", false),
                string_field("remoteHostId", "SSH 主机 id。", false),
                string_field("sessionId", "终端 session id。", false),
                number_field("limit", "返回数量上限。", false),
            ]),
        ),
        tool(
            "history.record",
            "记录命令历史",
            "把一条命令写入本地命令历史；疑似密钥、密码或 token 的命令会被服务跳过。",
            ToolCategory::History,
            ToolRiskLevel::Write,
            object_schema(vec![
                string_field("command", "命令内容。", true),
                enum_field(
                    "source",
                    "命令来源。",
                    false,
                    vec!["user", "ai", "snippet", "workflow", "broadcast", "tool"],
                ),
                enum_field("target", "目标类型。", false, vec!["local", "ssh"]),
                boolean_field("record", "当前会话是否允许记录历史。", false),
                string_field("sessionId", "终端 session id。", false),
                string_field("paneId", "前端 pane id。", false),
                string_field("tabId", "前端 tab id。", false),
                string_field("profileId", "本地 profile id。", false),
                string_field("remoteHostId", "SSH 主机 id。", false),
                string_field("cwd", "命令执行时工作目录。", false),
                string_field("shell", "命令执行时 shell。", false),
            ]),
        ),
        tool_with_policy(
            "history.delete",
            "删除命令历史",
            "删除一条本地命令历史记录。",
            ToolCategory::History,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Summary,
            true,
            true,
            object_schema(vec![string_field("entryId", "命令历史 id。", true)]),
        ),
        tool_with_policy(
            "history.clear",
            "清空命令历史",
            "清空本地命令历史记录。",
            ToolCategory::History,
            ToolRiskLevel::Destructive,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Full,
            true,
            true,
            object_schema(vec![]),
        ),
        tool(
            "diagnostics.runtime_health",
            "读取运行体检",
            "读取当前 Kerminal 进程、本机资源和本地数据目录的脱敏运行体检摘要。",
            ToolCategory::Diagnostics,
            ToolRiskLevel::Read,
            object_schema(vec![]),
        ),
        tool(
            "diagnostics.create_bundle",
            "生成诊断包",
            "生成本地脱敏 JSON 诊断包；不会上传或分享文件，只返回生成摘要和路径。",
            ToolCategory::Diagnostics,
            ToolRiskLevel::Write,
            object_schema(vec![]),
        ),
        tool_with_policy(
            "workflow.run",
            "执行工作流",
            "执行多步骤 snippet/workflow。当前只登记 schema，等待 workflow 切片启用。",
            ToolCategory::Workflow,
            ToolRiskLevel::Batch,
            ToolConfirmationPolicy::Always,
            ToolAuditPolicy::Full,
            false,
            false,
            object_schema(vec![string_field("workflowId", "工作流 id。", true)]),
        ),
    ]
}
