import type {
  AppearanceSettings,
  AppSettings,
  DesktopNotificationSettings,
  KeybindingSetting,
  SftpPerformanceSettings,
  TerminalAppearance,
} from "./settingsModel";
import {
  SFTP_GLOBAL_TRANSFERS_DEFAULT,
  SFTP_HOST_TRANSFERS_DEFAULT,
  SFTP_PACKET_BYTES_DEFAULT,
  SFTP_PIPELINE_DEPTH_DEFAULT,
  SFTP_TIMEOUT_SECONDS_DEFAULT,
  TERMINAL_INLINE_SUGGESTION_AUDIT_RETENTION_DAYS_DEFAULT,
  TERMINAL_INLINE_SUGGESTION_FEEDBACK_RETENTION_DAYS_DEFAULT,
} from "./settingsLimits";

export const defaultTerminalAppearance: TerminalAppearance = {
  autoReconnect: true,
  colorScheme: "kerminal",
  confirmCloseTab: true,
  cursorBlink: true,
  cursorStyle: "block",
  darkColorScheme: "kerminal",
  fontFamily:
    '"JetBrains Mono", "JetBrains Mono NL", "Cascadia Mono", Consolas, monospace',
  fontSize: 15,
  fontWeight: "normal",
  inlineSuggestion: {
    acceptKey: "rightArrow",
    enabled: true,
    productionHostPolicy: "restricted",
    providers: {
      git: true,
      history: true,
      remoteCommand: true,
      remotePath: true,
      spec: true,
    },
    remoteProbeEnabled: true,
    auditRetentionDays: TERMINAL_INLINE_SUGGESTION_AUDIT_RETENTION_DAYS_DEFAULT,
    feedbackRetentionDays:
      TERMINAL_INLINE_SUGGESTION_FEEDBACK_RETENTION_DAYS_DEFAULT,
  },
  lightColorScheme: "kerminal",
  lineHeight: 1.35,
  macOptionIsMeta: false,
  rightClickBehavior: "menu",
  scrollback: 5000,
  selectionCopy: false,
  showTabNumbers: false,
};

export const defaultAppearanceSettings: AppearanceSettings = {
  backgroundEnabled: false,
  backgroundFit: "cover",
  backgroundImagePath: "",
  backgroundOpacity: 100,
  interfaceLanguage: "system",
  windowOpacity: 100,
};

export const defaultDesktopNotificationSettings: DesktopNotificationSettings = {
  backgroundOnly: true,
  enabled: false,
  importantOnly: false,
  minDurationMs: 10_000,
  throttleMs: 30_000,
};

export const defaultKeybindings: KeybindingSetting[] = [
  {
    action: "settings.open",
    binding: "Ctrl+Shift+T",
    description: "打开设置。",
    editable: true,
    label: "打开设置",
    macBinding: "Cmd+,",
    scope: "global",
    windowsBinding: "Ctrl+Alt+S",
  },
  {
    action: "settings.keybindings",
    binding: "Ctrl+Shift+A",
    description: "打开快捷键与动作列表。",
    editable: true,
    label: "查看快捷键与动作",
    macBinding: "Cmd+Shift+A",
    scope: "global",
    windowsBinding: "Ctrl+Shift+A",
  },
  {
    action: "terminal.focus",
    binding: "Alt+F12",
    description: "显示终端工作区并收起右栏。",
    editable: true,
    label: "回到终端",
    macBinding: "Option+F12",
    scope: "global",
    windowsBinding: "Alt+F12",
  },
  {
    action: "terminal.newTab",
    binding: "Ctrl+Shift+T",
    description: "新建本地终端 tab。",
    editable: true,
    label: "新建本地终端",
    macBinding: "Cmd+Shift+T",
    scope: "workspace",
    windowsBinding: "Ctrl+Shift+T",
  },
  {
    action: "terminal.closeTab",
    binding: "Ctrl+F4",
    description: "关闭当前终端 tab。",
    editable: true,
    label: "关闭当前终端 tab",
    macBinding: "Cmd+W",
    scope: "workspace",
    windowsBinding: "Ctrl+F4",
  },
  {
    action: "terminal.closePane",
    binding: "Ctrl+Shift+W",
    description: "关闭当前分屏，多分屏时生效。",
    editable: true,
    label: "关闭当前分屏",
    macBinding: "Cmd+Shift+W",
    scope: "terminal",
    windowsBinding: "Ctrl+Shift+W",
  },
  {
    action: "terminal.splitHorizontal",
    binding: "Ctrl+Alt+Right",
    description: "在当前终端右侧创建分屏。",
    editable: true,
    label: "左右分屏",
    macBinding: "Ctrl+Option+Right",
    scope: "workspace",
    windowsBinding: "Ctrl+Alt+Right",
  },
  {
    action: "terminal.splitVertical",
    binding: "Ctrl+Alt+Down",
    description: "在当前终端下方创建分屏。",
    editable: true,
    label: "上下分屏",
    macBinding: "Ctrl+Option+Down",
    scope: "workspace",
    windowsBinding: "Ctrl+Alt+Down",
  },
  {
    action: "terminal.previousTab",
    binding: "Alt+Left",
    description: "切到左侧终端 tab。",
    editable: true,
    label: "上一个终端 tab",
    macBinding: "Cmd+Shift+[",
    scope: "workspace",
    windowsBinding: "Alt+Left",
  },
  {
    action: "terminal.nextTab",
    binding: "Alt+Right",
    description: "切到右侧终端 tab。",
    editable: true,
    label: "下一个终端 tab",
    macBinding: "Cmd+Shift+]",
    scope: "workspace",
    windowsBinding: "Alt+Right",
  },
  {
    action: "tool.agentLauncher",
    binding: "Alt+2",
    description: "打开 Agent Launcher。",
    editable: true,
    label: "打开 Agent Launcher",
    macBinding: "Cmd+2",
    scope: "global",
    windowsBinding: "Alt+2",
  },
  {
    action: "tool.system",
    binding: "Alt+3",
    description: "打开系统信息。",
    editable: true,
    label: "打开系统信息",
    macBinding: "Cmd+3",
    scope: "global",
    windowsBinding: "Alt+3",
  },
  {
    action: "tool.sftp",
    binding: "Alt+4",
    description: "打开 SFTP。",
    editable: true,
    label: "打开 SFTP",
    macBinding: "Cmd+4",
    scope: "global",
    windowsBinding: "Alt+4",
  },
  {
    action: "tool.ports",
    binding: "Alt+5",
    description: "打开端口转发。",
    editable: true,
    label: "打开端口转发",
    macBinding: "Cmd+5",
    scope: "global",
    windowsBinding: "Alt+5",
  },
  {
    action: "tool.snippets",
    binding: "Alt+6",
    description: "打开脚本片段。",
    editable: true,
    label: "打开脚本片段",
    macBinding: "Cmd+6",
    scope: "global",
    windowsBinding: "Alt+6",
  },
  {
    action: "tool.logs",
    binding: "Alt+7",
    description: "打开日志和审计记录。",
    editable: true,
    label: "打开日志",
    macBinding: "Cmd+7",
    scope: "global",
    windowsBinding: "Alt+7",
  },
];

export const defaultSftpPerformanceSettings: SftpPerformanceSettings = {
  globalTransfers: SFTP_GLOBAL_TRANSFERS_DEFAULT,
  hostTransfers: SFTP_HOST_TRANSFERS_DEFAULT,
  packetBytes: SFTP_PACKET_BYTES_DEFAULT,
  pipelineDepth: SFTP_PIPELINE_DEPTH_DEFAULT,
  timeoutSeconds: SFTP_TIMEOUT_SECONDS_DEFAULT,
};

export const defaultAppSettings: AppSettings = {
  appearance: defaultAppearanceSettings,
  desktopNotifications: defaultDesktopNotificationSettings,
  interfaceDensity: "comfortable",
  keybindings: defaultKeybindings,
  sftp: defaultSftpPerformanceSettings,
  terminal: defaultTerminalAppearance,
  themeMode: "dark",
};
