import type { McpGatewayManifest } from "../tool-panel/toolRegistryModel";

export const mcpGatewayManifest = {
  agent: {
    capabilities: [
      {
        description: "读取当前终端状态，准备终端输入、分屏和工具面板切换。",
        id: "terminal-workspace",
        title: "终端与工作区",
        toolCategories: ["terminal", "workspace"],
        toolExamples: ["terminal.write", "workspace.open_tool"],
      },
      {
        description: "浏览、预览和传输远程文件。",
        id: "sftp-files",
        title: "远程文件",
        toolCategories: ["sftp"],
        toolExamples: ["sftp.preview"],
      },
    ],
    defaultLanguage: "zh-CN",
    description: "Kerminal 应用内 AI 操作代理。",
    id: "kerminal-agent",
    name: "Kerminal Agent",
    operatingRules: ["远程、写入和破坏性操作必须走 Kerminal 确认。"],
    role: "面向开发者终端工作台的本地 AI 操作代理",
    title: "Kerminal Agent",
    toolCallProtocol: "使用标准 tool-call 调用已暴露 MCP 工具。",
  },
  generatedAt: "1",
  prompts: [
    {
      arguments: [
        { description: "用户希望完成的目标。", name: "goal", required: true },
      ],
      description: "根据用户目标选择 Kerminal Agent skill 和候选 MCP 工具。",
      name: "kerminal.agent.route",
      title: "选择 Agent Skill",
    },
  ],
  protocol: "kerminal-mcp/manifest",
  resources: [
    {
      description: "Kerminal Agent 的名称、角色和能力摘要。",
      dynamic: false,
      mimeType: "application/json",
      name: "agent-profile",
      title: "Agent 身份",
      uri: "kerminal://agent/profile",
    },
    {
      description: "用于把用户目标路由到 MCP 工具的 skills catalog。",
      dynamic: false,
      mimeType: "application/json",
      name: "agent-skills",
      title: "Agent Skills 目录",
      uri: "kerminal://agent/skills",
    },
    {
      description: "当前右侧工具、active tab、focused pane 和选中主机摘要。",
      dynamic: true,
      mimeType: "application/json",
      name: "application-context-current",
      title: "当前应用上下文",
      uri: "kerminal://application/context/current",
    },
  ],
  security: {
    auditEnabled: true,
    externalAccessEnabled: false,
    localOnly: true,
    notes: [],
    requiresKerminalConfirmation: true,
    secretsRedacted: true,
  },
  server: {
    description: "Kerminal MCP 能力清单。",
    name: "kerminal",
    title: "Kerminal",
    version: "test",
  },
  skills: [
    {
      description: "处理本地终端和工作区控制。",
      id: "terminal-workspace",
      origin: "system",
      promptGuidance: "写入终端前说明命令意图和风险。",
      title: "终端与工作区控制",
      toolIds: ["terminal.write", "workspace.open_tool"],
      triggerExamples: ["运行测试", "打开 SFTP 面板"],
      whenToUse: "用户要求运行本地命令、解释终端或切换工具面板时使用。",
    },
    {
      description: "处理远程文件浏览、预览、上传和下载。",
      id: "sftp-files",
      origin: "system",
      promptGuidance: "默认先列目录或预览再写入。",
      title: "SFTP 文件管理与传输",
      toolIds: ["sftp.preview"],
      triggerExamples: ["预览配置文件"],
      whenToUse: "用户要求查看远程目录、传输文件或改远程权限时使用。",
    },
  ],
  tools: {
    protocol: "mcp-tools/list",
    tools: [
      {
        annotations: {},
        audit: "summary",
        confirmation: "contextual",
        description: "向当前终端写入命令。",
        inputSchema: { properties: {}, required: [], type: "object" },
        name: "terminal.write",
        origin: "system",
        risk: "write",
        serverId: null,
        sourceToolId: "terminal.write",
        title: "写入终端",
      },
      {
        annotations: {},
        audit: "summary",
        confirmation: "contextual",
        description: "打开右侧工具面板。",
        inputSchema: { properties: {}, required: [], type: "object" },
        name: "workspace.open_tool",
        origin: "system",
        risk: "write",
        serverId: null,
        sourceToolId: "workspace.open_tool",
        title: "打开工具面板",
      },
      {
        annotations: {},
        audit: "summary",
        confirmation: "always",
        description: "预览远程文件。",
        inputSchema: { properties: {}, required: [], type: "object" },
        name: "sftp.preview",
        origin: "system",
        risk: "remote",
        serverId: null,
        sourceToolId: "sftp.preview",
        title: "预览远程文件",
      },
      {
        annotations: {},
        audit: "full",
        confirmation: "always",
        description: "Query a custom agent MCP server.",
        inputSchema: { properties: {}, required: [], type: "object" },
        name: "agent.query",
        origin: "custom",
        risk: "remote",
        serverId: "agent",
        sourceToolId: "agent.agent.query",
        title: "Agent Query",
      },
    ],
  },
  transports: [
    {
      args: [],
      command: null,
      description: "应用内 rmcp 网关。",
      endpoint: null,
      envKeys: [],
      headerKeys: [],
      id: "system.in_process_rmcp",
      kind: "in-process-rmcp",
      origin: "system",
      status: "enabled",
      title: "应用内 rmcp 网关",
    },
    {
      args: [],
      command: "kerminal mcp serve --transport stdio",
      description: "系统 MCP stdio 服务配置。",
      endpoint: null,
      envKeys: [],
      headerKeys: [],
      id: "system.stdio",
      kind: "stdio",
      origin: "system",
      status: "planned",
      title: "本地 stdio MCP Server",
    },
    {
      args: [],
      command: "tool_registry_mcp_http_start",
      description: "本地 Streamable HTTP MCP Server。",
      endpoint: "http://127.0.0.1:<dynamic>/mcp",
      envKeys: [],
      headerKeys: [],
      id: "system.local_http",
      kind: "streamable-http",
      origin: "system",
      status: "enabled",
      title: "本地 Streamable HTTP MCP Server",
    },
  ],
} satisfies McpGatewayManifest;
