export const TERMINAL_INLINE_SUGGESTION_RETENTION_DAYS_MIN = 1;
export const TERMINAL_INLINE_SUGGESTION_RETENTION_DAYS_MAX = 3650;
export const TERMINAL_INLINE_SUGGESTION_AUDIT_RETENTION_DAYS_DEFAULT = 30;
export const TERMINAL_INLINE_SUGGESTION_FEEDBACK_RETENTION_DAYS_DEFAULT = 365;

export const AI_CONTEXT_OUTPUT_BYTES_MIN = 512;
export const AI_CONTEXT_OUTPUT_BYTES_MAX = 24 * 1024;
export const AI_CONTEXT_OUTPUT_BYTES_DEFAULT = 12 * 1024;

export const SFTP_GLOBAL_TRANSFERS_MIN = 1;
export const SFTP_GLOBAL_TRANSFERS_MAX = 16;
export const SFTP_GLOBAL_TRANSFERS_DEFAULT = 4;
export const SFTP_HOST_TRANSFERS_MIN = 1;
export const SFTP_HOST_TRANSFERS_MAX = 8;
export const SFTP_HOST_TRANSFERS_DEFAULT = 2;
export const SFTP_PIPELINE_DEPTH_MIN = 1;
export const SFTP_PIPELINE_DEPTH_MAX = 256;
export const SFTP_PIPELINE_DEPTH_DEFAULT = 64;
export const SFTP_PACKET_BYTES_MIN = 32 * 1024;
export const SFTP_PACKET_BYTES_MAX = 256 * 1024;
export const SFTP_PACKET_BYTES_DEFAULT = 256 * 1024;
export const SFTP_TIMEOUT_SECONDS_MIN = 5;
export const SFTP_TIMEOUT_SECONDS_MAX = 300;
export const SFTP_TIMEOUT_SECONDS_DEFAULT = 30;
