import type {
  AiSecuritySettings,
  AppearanceSettings,
  AppSettings,
  KeybindingSetting,
  SftpPerformanceSettings,
  TerminalAppearance,
} from "./settingsModel";
import {
  AI_CONTEXT_OUTPUT_BYTES_DEFAULT,
  SFTP_GLOBAL_TRANSFERS_DEFAULT,
  SFTP_HOST_TRANSFERS_DEFAULT,
  SFTP_PACKET_BYTES_DEFAULT,
  SFTP_PIPELINE_DEPTH_DEFAULT,
  SFTP_TIMEOUT_SECONDS_DEFAULT,
  TERMINAL_INLINE_SUGGESTION_AUDIT_RETENTION_DAYS_DEFAULT,
  TERMINAL_INLINE_SUGGESTION_FEEDBACK_RETENTION_DAYS_DEFAULT,
} from "./settingsLimits";

export const DEFAULT_CUSTOM_SKILLS_DIRECTORY = "~/.kerminal/skills";

export const defaultTerminalAppearance: TerminalAppearance = {
  autoReconnect: true,
  colorScheme: "kerminal",
  confirmCloseTab: true,
  cursorBlink: true,
  cursorStyle: "block",
  darkColorScheme: "kerminal",
  fontFamily:
    '"JetBrains Mono", "JetBrains Mono NL", "Cascadia Mono", Consolas, monospace',
  fontSize: 15,
  fontWeight: "normal",
  inlineSuggestion: {
    acceptKey: "rightArrow",
    enabled: true,
    productionHostPolicy: "restricted",
    providers: {
      ai: false,
      git: true,
      history: true,
      remoteCommand: true,
      remotePath: true,
      spec: true,
    },
    remoteProbeEnabled: true,
    auditRetentionDays: TERMINAL_INLINE_SUGGESTION_AUDIT_RETENTION_DAYS_DEFAULT,
    feedbackRetentionDays:
      TERMINAL_INLINE_SUGGESTION_FEEDBACK_RETENTION_DAYS_DEFAULT,
  },
  lightColorScheme: "kerminal",
  lineHeight: 1.35,
  macOptionIsMeta: false,
  rightClickBehavior: "menu",
  scrollback: 5000,
  selectionCopy: false,
  showTabNumbers: false,
};

export const defaultAppearanceSettings: AppearanceSettings = {
  backgroundEnabled: false,
  backgroundFit: "cover",
  backgroundImagePath: "",
  backgroundOpacity: 100,
  interfaceLanguage: "system",
  windowOpacity: 100,
};

export const defaultKeybindings: KeybindingSetting[] = [
  {
    action: "settings.open",
    binding: "Ctrl+Shift+T",
    description:
      "参考 IntelliJ IDEA 的设置入口：Windows 使用 Ctrl+Alt+S，macOS 使用 Cmd+,。",
    editable: true,
    label: "打开设置",
    macBinding: "Cmd+,",
    scope: "global",
    windowsBinding: "Ctrl+Alt+S",
  },
  {
    action: "settings.keybindings",
    binding: "Ctrl+Shift+A",
    description:
      "参考 IDEA 的 Find Action 习惯，当前直接打开快捷键与动作列表。",
    editable: true,
    label: "查看快捷键与动作",
    macBinding: "Cmd+Shift+A",
    scope: "global",
    windowsBinding: "Ctrl+Shift+A",
  },
  {
    action: "terminal.focus",
    binding: "Alt+F12",
    description:
      "参考 IDEA Terminal 工具窗口；显示终端工作区并收起右侧工具面板。",
    editable: true,
    label: "回到终端",
    macBinding: "Option+F12",
    scope: "global",
    windowsBinding: "Alt+F12",
  },
  {
    action: "terminal.newTab",
    binding: "Ctrl+Shift+T",
    description: "新建本地终端 tab，保留终端应用常见的新建标签习惯。",
    editable: true,
    label: "新建本地终端",
    macBinding: "Cmd+Shift+T",
    scope: "workspace",
    windowsBinding: "Ctrl+Shift+T",
  },
  {
    action: "terminal.closeTab",
    binding: "Ctrl+F4",
    description: "关闭当前终端 tab，尽量贴近 IDEA 关闭编辑器 tab 的习惯。",
    editable: true,
    label: "关闭当前终端 tab",
    macBinding: "Cmd+W",
    scope: "workspace",
    windowsBinding: "Ctrl+F4",
  },
  {
    action: "terminal.closePane",
    binding: "Ctrl+Shift+W",
    description: "关闭当前分屏；只有多分屏时生效，避免误关最后一个终端。",
    editable: true,
    label: "关闭当前分屏",
    macBinding: "Cmd+Shift+W",
    scope: "terminal",
    windowsBinding: "Ctrl+Shift+W",
  },
  {
    action: "terminal.splitHorizontal",
    binding: "Ctrl+Alt+Right",
    description:
      "在当前终端右侧创建分屏，沿用 IDEA 风格的 Ctrl/Option 方向键组合。",
    editable: true,
    label: "左右分屏",
    macBinding: "Ctrl+Option+Right",
    scope: "workspace",
    windowsBinding: "Ctrl+Alt+Right",
  },
  {
    action: "terminal.splitVertical",
    binding: "Ctrl+Alt+Down",
    description: "在当前终端下方创建分屏，与左右分屏形成方向键配对。",
    editable: true,
    label: "上下分屏",
    macBinding: "Ctrl+Option+Down",
    scope: "workspace",
    windowsBinding: "Ctrl+Alt+Down",
  },
  {
    action: "terminal.previousTab",
    binding: "Alt+Left",
    description:
      "切到左侧终端 tab，参考 IDEA 在 tab/位置之间切换的方向键心智。",
    editable: true,
    label: "上一个终端 tab",
    macBinding: "Cmd+Shift+[",
    scope: "workspace",
    windowsBinding: "Alt+Left",
  },
  {
    action: "terminal.nextTab",
    binding: "Alt+Right",
    description: "切到右侧终端 tab，和上一个 tab 保持成对操作。",
    editable: true,
    label: "下一个终端 tab",
    macBinding: "Cmd+Shift+]",
    scope: "workspace",
    windowsBinding: "Alt+Right",
  },
  {
    action: "tool.ai",
    binding: "Alt+2",
    description:
      "打开 Kerminal Agent 工具窗口，参考 IDEA Alt/Cmd+数字切换工具窗口。",
    editable: true,
    label: "打开 Kerminal Agent",
    macBinding: "Cmd+2",
    scope: "global",
    windowsBinding: "Alt+2",
  },
  {
    action: "tool.system",
    binding: "Alt+3",
    description: "打开系统信息工具窗口，使用工具窗口编号快速切换。",
    editable: true,
    label: "打开系统信息",
    macBinding: "Cmd+3",
    scope: "global",
    windowsBinding: "Alt+3",
  },
  {
    action: "tool.sftp",
    binding: "Alt+4",
    description: "打开 SFTP 工具窗口，便于在终端和文件浏览之间切换。",
    editable: true,
    label: "打开 SFTP",
    macBinding: "Cmd+4",
    scope: "global",
    windowsBinding: "Alt+4",
  },
  {
    action: "tool.ports",
    binding: "Alt+5",
    description: "打开端口转发工具窗口。",
    editable: true,
    label: "打开端口转发",
    macBinding: "Cmd+5",
    scope: "global",
    windowsBinding: "Alt+5",
  },
  {
    action: "tool.snippets",
    binding: "Alt+6",
    description: "打开脚本片段工具窗口。",
    editable: true,
    label: "打开脚本片段",
    macBinding: "Cmd+6",
    scope: "global",
    windowsBinding: "Alt+6",
  },
  {
    action: "tool.logs",
    binding: "Alt+7",
    description: "打开日志工具窗口，快速查看会话和 AI 审计记录。",
    editable: true,
    label: "打开日志",
    macBinding: "Cmd+7",
    scope: "global",
    windowsBinding: "Alt+7",
  },
];

export const defaultAiSecuritySettings: AiSecuritySettings = {
  allowDestructiveTools: false,
  commandApprovalPolicy: "risky",
  commandTimeoutSeconds: 30,
  contextMaxOutputBytes: AI_CONTEXT_OUTPUT_BYTES_DEFAULT,
  customInstructions: "",
  includeCommandHistory: false,
  mcp: {
    servers: [],
    skillDirectories: [
      {
        enabled: true,
        id: "user-skills",
        path: DEFAULT_CUSTOM_SKILLS_DIRECTORY,
      },
    ],
  },
  requireRemoteApproval: true,
  terminalTailLines: 50,
};

export const defaultSftpPerformanceSettings: SftpPerformanceSettings = {
  globalTransfers: SFTP_GLOBAL_TRANSFERS_DEFAULT,
  hostTransfers: SFTP_HOST_TRANSFERS_DEFAULT,
  packetBytes: SFTP_PACKET_BYTES_DEFAULT,
  pipelineDepth: SFTP_PIPELINE_DEPTH_DEFAULT,
  timeoutSeconds: SFTP_TIMEOUT_SECONDS_DEFAULT,
};

export const defaultAppSettings: AppSettings = {
  ai: defaultAiSecuritySettings,
  appearance: defaultAppearanceSettings,
  interfaceDensity: "comfortable",
  keybindings: defaultKeybindings,
  sftp: defaultSftpPerformanceSettings,
  terminal: defaultTerminalAppearance,
  themeMode: "dark",
};
