//! SFTP 与端口转发工具目录。
//!
//! @author kongweiguang

use crate::models::mcp_server::{ToolCategory, ToolDefinition};

use super::super::schema::{
    boolean_field, enum_field, number_field, object_schema, string_field, tool, tool_with_exposure,
    ToolEffect,
};

pub(super) fn sftp_tools() -> Vec<ToolDefinition> {
    vec![
        tool(
            "sftp.list",
            "列出远程目录",
            "读取当前 SSH 主机上的远程目录内容。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程目录路径。", true),
            ]),
        ),
        tool(
            "sftp.rename",
            "重命名远程路径",
            "重命名远程文件或目录；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("fromPath", "原远程路径。", true),
                string_field("toPath", "新远程路径。", true),
            ]),
        ),
        tool(
            "sftp.move",
            "移动远程路径",
            "移动远程文件或目录；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("fromPath", "原远程路径。", true),
                string_field("toPath", "目标远程路径。", true),
            ]),
        ),
        tool(
            "sftp.preview",
            "预览远程文件",
            "读取远程文本文件预览。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程文件路径。", true),
                number_field("maxBytes", "最多读取字节数。", false),
            ]),
        ),
        tool(
            "sftp.download",
            "下载远程文件",
            "下载远程文件到本地；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("remotePath", "远程文件路径。", true),
                string_field("localPath", "本地保存路径。", true),
            ]),
        ),
        tool(
            "sftp.upload",
            "上传本地文件",
            "上传本地文件到远程；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("localPath", "本地文件路径。", true),
                string_field("remotePath", "远程保存路径。", true),
            ]),
        ),
        tool_with_exposure(
            "sftp.delete",
            "删除远程文件",
            "删除远程文件或空目录；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Destructive,
            true,
            true,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程路径。", true),
                boolean_field("directory", "是否按空目录删除。", false),
            ]),
        ),
        tool(
            "sftp.create_directory",
            "创建远程目录",
            "创建远程目录；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程目录路径。", true),
            ]),
        ),
        tool(
            "sftp.chmod",
            "修改远程权限",
            "修改远程路径权限；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("path", "远程路径。", true),
                string_field("mode", "八进制权限模式，例如 644 或 0755。", true),
            ]),
        ),
        tool(
            "sftp.upload_directory",
            "上传本地目录",
            "递归上传本地目录；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("localPath", "本地目录路径。", true),
                string_field("remotePath", "远程保存路径。", true),
            ]),
        ),
        tool(
            "sftp.download_directory",
            "下载远程目录",
            "递归下载远程目录；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("remotePath", "远程目录路径。", true),
                string_field("localPath", "本地保存路径。", true),
            ]),
        ),
        tool(
            "sftp.transfer.enqueue",
            "创建 SFTP 传输任务",
            "加入 SFTP 队列，返回任务 id。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("remotePath", "远程路径。", true),
                string_field("localPath", "本地路径。", true),
                enum_field("direction", "传输方向。", true, vec!["upload", "download"]),
                enum_field("kind", "传输对象类型。", true, vec!["file", "directory"]),
            ]),
        ),
        tool(
            "sftp.transfer.list",
            "列出 SFTP 传输任务",
            "读取 SFTP 队列、状态和进度。",
            ToolCategory::Sftp,
            ToolEffect::Read,
            object_schema(vec![]),
        ),
        tool(
            "sftp.transfer.cancel",
            "取消 SFTP 传输任务",
            "取消指定传输任务；调用前确认由 MCP host 负责。",
            ToolCategory::Sftp,
            ToolEffect::Remote,
            object_schema(vec![string_field("transferId", "SFTP 传输任务 id。", true)]),
        ),
        tool(
            "sftp.transfer.clear_completed",
            "清理已结束 SFTP 任务",
            "清理成功、失败或取消的任务。",
            ToolCategory::Sftp,
            ToolEffect::Write,
            object_schema(vec![]),
        ),
        tool(
            "server_info.snapshot",
            "读取服务器信息",
            "读取 SSH 主机 CPU、内存、磁盘、网络和运行时间摘要。",
            ToolCategory::ServerInfo,
            ToolEffect::Remote,
            object_schema(vec![string_field("hostId", "远程主机 id。", true)]),
        ),
        tool(
            "port_forward.create",
            "创建端口转发",
            "创建 SSH 端口转发，包括本机和远端 SOCKS 转发。",
            ToolCategory::PortForward,
            ToolEffect::Remote,
            object_schema(vec![
                string_field("hostId", "远程主机 id。", true),
                string_field("name", "用户可见转发名称。", false),
                enum_field(
                    "kind",
                    "转发类型。",
                    true,
                    vec!["local", "remote", "remoteDynamic", "dynamic"],
                ),
                enum_field(
                    "proxyProtocol",
                    "SOCKS 转发代理协议。",
                    false,
                    vec!["socks5"],
                ),
                string_field("bindHost", "监听地址，默认 127.0.0.1。", false),
                string_field("localBindHost", "本机侧监听地址或本机代理绑定地址。", false),
                string_field("remoteBindHost", "远端监听地址。", false),
                number_field("sourcePort", "监听端口；remote 时为远端端口。", true),
                string_field("targetHost", "目标主机；dynamic 转发可为空。", false),
                number_field("targetPort", "目标端口；dynamic 转发可为空。", false),
                enum_field(
                    "remoteAccessScope",
                    "远端监听范围；非 loopback 需 GatewayPorts。",
                    false,
                    vec!["loopback", "privateNetwork", "allInterfaces", "custom"],
                ),
                enum_field(
                    "proxyApplyScope",
                    "代理应用范围；MCP 默认不写远端 profile。",
                    false,
                    vec![
                        "none",
                        "currentTerminal",
                        "futureTerminals",
                        "userProfile",
                        "toolOnly",
                    ],
                ),
            ]),
        ),
        tool(
            "port_forward.list",
            "列出端口转发",
            "读取端口转发配置和状态。",
            ToolCategory::PortForward,
            ToolEffect::Read,
            object_schema(vec![]),
        ),
        tool(
            "port_forward.close",
            "停止端口转发",
            "停止转发会话并保留配置；调用前确认由 MCP host 负责。",
            ToolCategory::PortForward,
            ToolEffect::Remote,
            object_schema(vec![string_field("forwardId", "端口转发会话 id。", true)]),
        ),
    ]
}
